### ISSUE TITLE
update flox prompt default branding colors

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1061]
# Acceptance Criteria

Default prompt colors are updated...

_from_
FLOX_PROMPT_COLOR_1=61 
FLOX_PROMPT_COLOR_2=216

_to_
FLOX_PROMPT_COLOR_1=99 
FLOX_PROMPT_COLOR_2=141

### flox
* color: #875FFF ([99](https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg))
* bold

### environment name(s)
* color: #AF87FF ([141](https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg))
* NO bold

### NO_COLOR support
Flox should support NO_COLOR setting: https://no-color.org/ 

### Color previews on various backgrounds
![purple shades - dark bg - 256adjusted](https://github.com/flox/flox/assets/2687382/dfeaf3db-4d8c-4dff-8920-de96dd3db896)
![purple shades - light bg - 256adjusted](https://github.com/flox/flox/assets/2687382/b2304131-f558-46cd-9c2a-f5eea3a13370)
![purple shades - neutral bg - 256adjusted](https://github.com/flox/flox/assets/2687382/2e4d8c85-af87-484f-932d-48776d51aa24)

**Comment by ghudgins** [comment]
@rossturk @jennymahmoudi ping on the requirements for this

**Comment by jennymahmoudi** [comment]
I abandoned any black/white options because the background color was too invasive, and forcing black or white as text color does not work across multiple background colors. 

So back to an actual color, the purple is the secondary-color of choice in the brand system. I used 2 shades from the color palette that worked best across light and dark backgrounds. Then I chose the closest match for those colors from https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg  -- If I'm not limited to those colors, please let me know!

The contrast is not perfect, but it performs the same as what we had before with the old brand colors (not a regression).

**Comment by jennymahmoudi** [comment]
Just for reference, from our slack conversation about naming these colors:

FLOX_PROMPT_COLOR_1=99    #indigo400
FLOX_PROMPT_COLOR_2=141  #indigo300

![image](https://github.com/flox/flox/assets/2687382/64f74546-8e91-45df-b5e4-8a42f4e96824)

**Comment by ghudgins** [comment]
verified
