### ISSUE TITLE
flox init reads .nvmrc and suggests installation/config

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1063]
# Acceptance Criteria

**Given** the project has `.nvmrc` file with a version that's in Flox (18.18.2 at the time of this writing)
**And** i'm in the project directory
**When** I `flox init`
**And** Flox has a matching node version
**Then** I see an interactive prompt

```
Flox detected a .nvmrc

node projects typically need:
* nodejs@18.18.2

Would you like Flox to apply this suggestion? 
You can always revisit the environment's declaration with 'flox edit'

>Yes 
No
Show environment manifest

```

_node version doesn't exist_
**Given** the project has `.nvmrc` file with a version that's not in Flox (18.18.0 at the time of this writing)
**And** i'm in the project directory
**When** I `flox init`
**Then** I see Flox has created the environment without detecting the .nvmrc

# Details

No shell hook

**Comment by ysndr** [comment]
how will this work together with #1073/#1072?
Are these separate integrations or additions to this one?
Givent hat we likely dont want multiple integrations installing versions of nodejs it's likely the latter?

**Comment by mkenigs** [comment]
It seems like we should do:
Check for nvmrc, use that node version if we have it.
If there's' no nvmrc, check for `node` version in `engines` in `package.json`, and use that.
Otherwise use latest node

If there's a package.json && there's a package-lock.json, offer to add an `npm i` hook
If there's a package.json && there's a yarn.lock, offer to add a yarn hook
If there's just a package.json, offer to add an `npm i` hook
If there's both `package-lock.json` and `yarn.lock`, offer a choice of hook

**Comment by ghudgins** [comment]
verified
