### ISSUE TITLE
Port 1 integration or functional test to pytest

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1163]
It may be easier to write some of our integration tests using `pytest` rather than `bats`. There's some prior work in https://github.com/flox/flox/pull/608. After porting 1 test, we can discuss as a team whether we want to use pytest more going forward

AC:
- 1 integration or functional test is run with pytest

**Comment by zmitchell** [comment]
I think in order for us to have productive discussion about whether to use `pytest` more going forward we need the test that's written here to reflect our current test suite. That means something like:
- A shared home directory fixture for most tests to reuse
- An isolated home directory fixture for _some_ tests to use
- The ability to run tests in parallel so we don't regress in terms of execution time.
- The ability to mark certain tests as needing to run serially.

Creating fixtures isn't hard, but it is added complexity on top of creating a single test, so I wanted to bring that up in case we didn't want to add that to the scope of the ticket.

`pytest` by default doesn't run tests in parallel. I did some homework into the parallel case and there's a `pytest` plugin called `pytest-xdist` (already in nixpkgs) that spawns workers and distributes tests to those workers. That solves the "must run in parallel" case. You can also mark certain tests as needing to run as a "group", which really means that they just run on a single worker, which means they'll be run serially. This also means that we'll need to write test fixtures using locking mechanisms so that global fixtures (like a shared home directory) don't get created more than once.

Knowing that there's a solution to the parallel test situation is nice, but before we do any larger adoption I'd want to test that out to de-risk it. Each worker does its own test collection, running, etc as if you had run `pytest` multiple times on subsets of the tests, so there could be unexpected interactions there.

So, what I'd like to do is amend the acceptance criteria to this:
- 3 integration tests
- A fixture for a shared home directory
- Make 2 of the tests run serially, and make the third test run in parallel with the other two

Thoughts?

**Comment by mkenigs** [comment]
Sounds good to me. I think making sure parallel and serial works well is important. There's several different possible ways we could isolate the various dirs used by flox, but so long as we have both suite wide and test specific fixtures, I'm pretty confident we could do any of them, so I don't think getting that right is too important yet.

**Comment by zmitchell** [comment]
Sounds good, I'll focus on the parallel part

**Comment by zmitchell** [comment]
Here's the original test I decided to port:
```text
# bats test_tags=activate,activate:inplace-modifies
@test "'flox activate' modifies the current shell (bash)" {

  # set a hook
  sed -i -e "s/^\[profile\]/${HELLO_PROFILE_SCRIPT//$'\n'/\\n}/" "$PROJECT_DIR/.flox/env/manifest.toml"
  # set vars
  sed -i -e "s/^\[vars\]/${VARS//$'\n'/\\n}/" "$PROJECT_DIR/.flox/env/manifest.toml"
  "$FLOX_BIN" install hello

  run bash -c 'eval "$("$FLOX_BIN" activate)"; type hello; echo $foo'
  assert_success
  # assert hook
  assert_line "Welcome to your flox environment!"
  # assert installed package
  assert_line --partial "hello is $(realpath $PROJECT_DIR)/.flox/run/"
  # assert var
  assert_line "baz"
}
```

Here's the test ported to Python (note that this one is parameterized by shell, so it's run one time for `bash` and one time for `zsh`):
```python
@pytest.mark.parametrize("shell", SUPPORTED_SHELLS)
def test_activate_modifies_shell(shell, flox, flox_env, run) -> None:
    output = run([shell, "-c", f"{flox} init"])
    assert flox_env.path.exists()
    assert (flox_env.path / ".flox").exists()
    with flox_env.manifest_path().open("r") as f:
        manifest = tomlkit.load(f)
    manifest["profile"]["common"] = tomlkit.string(
        HELLO_PROFILE_COMMON, multiline=True, escape=False
    )
    manifest["vars"]["foo"] = "baz"
    with flox_env.manifest_path().open("w") as f:
        tomlkit.dump(manifest, f)
    run([shell, "-c", f"{flox} install hello"])
    output = run([shell, "-c", f"eval $({flox} activate); type hello; echo $foo"])
    output.check_returncode()
    assert "Welcome to your flox environment" in output.stdout
    assert f"hello is {flox_env.run_path.absolute}" in output.stdout
    assert "baz" in output.stdout
```

This test fails with the following error, indicating that `hello` is not found in the environment:
```console
>       assert "Welcome to your flox environment" in output.stdout
E       AssertionError: assert 'Welcome to your flox environment' in '\n'
E        +  where '\n' = CompletedProcess(args=['bash', '-c', 'eval $(flox activate); type hello; echo $foo'], returncode=0, stdout='\n', stderr='bash: line 1: type: hello: not found\n').stdout
```

The fact that this test passes in our `bats` test suite and fails when written how you would expect to be able to write it via `pytest` is a mark against using `pytest` for our CLI test suite. There may be a simple explanation for this particular failure, but it's one example of a category of error that simply doesn't exist when tests are written in as shell code directly.

**Comment by zmitchell** [comment]
I made a list of pros and cons while I was working on this:

# Pros
- Python is an ergonomic language for manipulating data
- `pytest` makes it trivial to write reusable test fixtures
- Python is generally easier to read than Bash when manipulating data
- `pytest` allows you to parameterize tests, meaning you can write fewer tests for the same coverage.
- `pytest` provides a nice summary about which tests failed at the end
- `pytest` has built-in support (via plugin) for distributing tests across cores/machines
- You can pause the test in the middle via the Python built-in function `breakpoint()`

# Cons
- With `pytest` you introduce ambiguity as to where the root cause lies when a test fails
    - If you had a problem that involved needing a controlling terminal, would you even know?
    - When treating TOML as a dictionary, what does the resulting string look? Do you need to provide quotes, are they automatically escaped, etc?
    - When there's a breakage, is it your test, how you're calling Flox from the test, or is it Flox?
- There's not less escaping, there's just different escaping
- It looks less like how a user would use the product
- It can be more verbose than `bats`
- We now have to bring in an entirely separate ecosystem used _only_ for testing
- Building infrastructure to make sure that `flox` is called properly from Python introduces an entirely new layer of complexity and a set of tooling that we must maintain.

**Comment by mkenigs** [comment]
Discussed and we won't use pytest for now
