### ISSUE TITLE
Intermittent hang in `pkgdb`

### ISSUE THREAD

**Issue by billlevine** [flox/flox#1223]
**Describe the bug:**
`pkgdb` hangs intermittently.  Evidence strongly suggests an error with `pkgdb` trying to write more than 64k to a pipe.  

See CLI error from Rust side of things reporting an EOF while trying to parse JSON at position 65536.

From Slack community: https://floxcommunitygroup.slack.com/archives/C06NYALM8P8/p1711171882136949

**Steps to reproduce:**

**Screenshots/terminal output (if relevant):**
<img width="1841" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1VJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4725124026b4685e24e489732a0390f91a09b33/Screenshot%202024-03-23%20at%2012.28.47%E2%80%AFPM.png" alt="Screenshot 2024-03-23 at 12.28.47 PM.png" />

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1lJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4231eed607bf65c8da8c1e062c8a20343d107356/Screenshot%202024-03-25%20at%202.50.00%E2%80%AFPM.png" alt="Screenshot 2024-03-25 at 2.50.00 PM.png" />

** flox Version (run `flox --version` if possible): **
Seen on `v1.0.1`

** `uname -a` output: **

Seen on multiple.

**Comment by billlevine** [comment]
For multiple operations, the Rust side of the CLI will exec `pkgdb` and read it's `stdout` via pipes to obtain it's response.  The error reported strongly suggests one of these responses is being truncated.  It could be that there is no concurrent processing of the data, and `pkgdb` will write up to the 64k pipe buffer limit (reasonable assumption) and hang writing for space to be freed from the reader.  Terminating that `pkgdb` instance would let things continue, but with truncated data.

Running `flox` commands with `RUST_LOG=debug` could help show what it's trying to do with `pkgdb` and possibly the invocation for simpler reproduction.  `strace` if available with filters for `exec` could also help with this.  Or even filter on `write` syscalls to try and get a look at the data that might be coming back.

Another way to potentially prove out this theory, would be to hack the Rust invocation of `pkgdb` to intentionally bloat the response.  For example, searches default to 10 items in the response, but you could add `--query-limit 500` to the invocation of the `pkgdb search` command.  Then search for `a` or something to trigger a >64k sized response.

I don't _think_ there are instances of `pkgdb` communicating with itself via pipes.  It does however fork while scraping for packages, so there could be multiple `pkgdb`s in the debugger.  But that mechanism _should_ be complete before `pkgdb` tries to respond by writing to `stdout` to send info back to the Rust process.  I only add this info to be cautious of extra `pkgdb` threads and automatically conflating that with the issue at hand.  Although they may very well be related.

**Comment by b7r6** [comment]
I don't have much to add since I looked at this last other than to clarify I've never seen it emit an error that made it to the top of the fork tree without getting a signal. I don't have a cap/gist handy but I'll make a note to get ps -ef output next time I see it wedged.

Based on my admittedly limited knowledge of how the forking etc. is done, I think a lock file race is strongly implicated. It's a little tricky for me personally because I'm very new to darwin as anything other than an appliance, so I don't know what people do in lieu of e.g. strace, and I somewhat rarely catch it on Linux at current release (almost never on x86_64-linux).

What's the most useful set of diagnostics I could grab with darwin the next time it acts up?

**Comment by zmitchell** [comment]
Can you post the manifest that you were editing that caused this error?

> so I don't know what people do in lieu of e.g. strace

People often use DTrace on macOS, but there's a [hardware bug](https://forums.developer.apple.com/forums/thread/735939) on recent Mac laptops that will cause your laptop to hang if it's been put to sleep since it was booted :)

**Comment by zmitchell** [comment]
I was able to reproduce the hang locally and put together a fix: https://github.com/flox/flox/pull/1238
