### ISSUE TITLE
bash prompt is garbled on macOS with `eval "$(flox activate)"

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1252]
STR:
```
$ flox init
...

$ /bin/bash
...

bash-3.2$ flox activate
✅ You are now using the environment in current directory.
To stop using this environment, type 'exit'

flox [tmp mkenigs/default] Matthews-MacBook-Pro-2% exit

bash-3.2$ eval "$(flox activate)"
flox [tmp mkenigs/default] %m%#
```

Expected:
When using `eval "$(flox activate)"`, the prompt should look the same as when using `flox activate` rather than having `%m%#`

Version and system info:
```
$ flox --version
Version: 1.0.2
$ uname -a
Darwin Matthews-MacBook-Pro-2.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64
```

**Comment by limeytexan** [comment]
This is caused by a collision of `SET_PROMPT_SH` being saved to the environment by zsh, and then a subsequent bash activation will attempt to use it. It's an easy fix to establish separate `SET_PROMPT_{BASH,ZSH}_SH` variables and I have added this in an upcoming draft PR that I'll be logging momentarily.
