### ISSUE TITLE
[spike] compare openapi-generator and progenitor

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1263]
Generate a client using https://github.com/oxidecomputer/progenitor and one with https://github.com/OpenAPITools/openapi-generator.

Create a list of pros and cons for each for our usage, and give a recommendation for which we should use.

**Comment by billlevine** [comment]
Here's a sample API spec.  A few notes:
- This was generated by the code on the [FastAPI](https://github.com/flox/catalog-server/tree/FastAPI) branch of the catalog-server repo.
- That branch defines data models and endpoints using FastAPI which provides a swagger-ui interface automatically, along with a download link to the openapi spec.
- The spec attached here is a work in progress, incomplete, and is un-reviewed.
- It is representative of what we expect to generate.
- Requests for any adjustments to accommodate various client code generators are welcome

[openapi.json](https://github.com/flox/flox/files/14841025/openapi.json)

**Comment by ysndr** [comment]
# openapi generator 

https://openapi-generator.tech/docs/generators/rust

```
# nix shell nixpkgs#openapi-generator-cli
openapi-generator-cli  generate -i https://github.com/flox/flox/files/14841025/openapi.json -g rust
```


## Observations

- pretty much a cross language standard
- can access schemas via url
- generation of spec version 3.1.0 is "in development":

> Generation using 3.1.0 specs is in development and is not officially supported yet. If you would like to expedite development, please consider woking on the open issues in the 3.1.0 project: https://github.com/orgs/OpenAPITools/projects/4/views/1 and reach out to our team on Slack at https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g

- generates an entire client library crate

## Manifest

- interprets info.version -- causes incorrect version in manifest as `v1 -> 1` is not correct semver
- interprets lincense from schema (missing in schema)
- 


### Dependencies:

```
serde = "^1.0"
serde_derive = "^1.0"
serde_with = "^2.0"
serde_json = "^1.0"
url = "^2.2"
uuid = { version = "^1.0", features = ["serde", "v4"] }
```

- installs an outdated `serde_with` (`^2.0`, upstream at `3.7.0` -- nb, we are not using 3.* internally either yet )
- installs an outdated `reqwest` (`^0.11`, upstream at `0.12.2`)

## Code

- does not compile out of the box, may be due to the schema
- exports two modules: `apis` (paths) and `models` (components)

### Models

- models with `anyOf` with `null` are generated with a faux type: `AnyOfLessThanGreaterThan` 
  - for instances with `anyOf{ SomeType, null }` it might be more correct to omit them from the `required` field
- `anyOf` (and `oneOf`) do not generate `enum`s, but a combined object -- weird 🤔:

```json
"outputs": {
  "anyOf": [
    { "$ref": "#/components/schemas/PackageDescriptor" },
    { "$ref": "#/components/schemas/CatalogPage" }
  ],
  "title": "Outputs"
},
```

```rust
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Outputs {
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<serde_json::Value>,
    #[serde(rename = "pkgPath", deserialize_with = "Option::deserialize")]
    pub pkg_path: Option<serde_json::Value>,
    #[serde(rename = "semver", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub semver: Option<Option<serde_json::Value>>,
    #[serde(rename = "version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub version: Option<Option<serde_json::Value>>,
    #[serde(rename = "derivation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub derivation: Option<Option<serde_json::Value>>,
    #[serde(rename = "page", deserialize_with = "Option::deserialize")]
    pub page: Option<serde_json::Value>,
    #[serde(rename = "url", deserialize_with = "Option::deserialize")]
    pub url: Option<serde_json::Value>,
    #[serde(rename = "packages", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub packages: Option<Option<serde_json::Value>>,
}
```

### APIs

- local variables are all prefixed with `local_var_`?!
- api methods are pretty dense, but make nothing surprising happens
- api methods are all `async` (can be configurable)
- each api call ha its own error type, i.e. `Error<ActualErrorResponseJson>`


- example methods signature:

```
pub async fn operation_id(configuration: &configuration::Configuration, model_for_params: crate::models::_ ) -> Result<crate::models::_, Error<ResolveApiV1CatalogResolvePostError>> {

```

### Comments
The generated file docs are a bit weird, i.e. not module level docs but containing some markdown..
No big deal i think, but not great either

```
/*
 * Flox Catalog Server
 *
 *  # Flox Catalog API  ## Markdown  Section  ## More markdown  You will be able to:  - **Search** for packages 
 *
 * The version of the OpenAPI document: v1.2.3
 * Contact: engineering@floxdev.com
 * Generated by: https://openapi-generator.tech
 */
```

# progenitor cli

- requires rustc > 1.74, we are pinned at `1.73`
- does not support openapi spec `3.1.0`
- error messages are rather uninformative

```
thread 'main' panicked at /Users/yannik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/progenitor-impl-0.6.0/src/to_schema.rs:621:39:
not yet implemented: invalid type: null
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by billlevine** [comment]
Updated spec at v3.0.2.
This is a 3.1.0 spec as generated by the latest FastAPI with a manual 'conversion' to change the `anyOf` use  with `type: null` to use the OpenAPI `nullable: True` instead.

[openapi302.json](https://github.com/flox/flox/files/14856926/openapi302.json)

**Comment by ysndr** [comment]
with the manually edited 3.0.2 spec progenitor actually generates something now:

# progenitor-cli (spec 3.0.2)

https://github.com/oxidecomputer/progenitor

```
cargo progenitor --input ./openapi302.json --output progenitor-cli --name catalogapi --version 1.0.0
```

## Observations

- apparently, progenitor really just doesnt like `null`!
- the error messages and outputs are really barebones -- effectively just serde json parsing errors and thats it.
- little customization on the cli
- does not allow writing updates only (cargo toml is overridden every time)

## Manifest

- license provided by cli
- version provided by cli

### Dependencies

```
[dependencies]
bytes = "1.5.0"
futures-core = "0.3.30"
progenitor-client = "0.6.0"
reqwest = { version = "0.11.24", default-features=false, features = ["json", "stream"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_urlencoded = "0.7.1"
```

- installs `reqwest` at version `0.11`, upstream at `0.12` (since two weeks, so i have hopes they update soon too)
- no surprising deps otherwise

## Code

- generates single `lib.rs` file, containing a `types` module and a `Client` interface.
- generates doc comments from `description` fields
- embeds original spec definitions in the doc comments
- correctly embeds markdown comments with line breaks

### types

- supports enums 🎉
	- enum names are weird if containing primitive types
	```json
	"loc": {
	  "items": { "anyOf": [{ "type": "string" }, { "type": "integer" }] },
	  "type": "array",
	  "title": "Location"
	},
	```
	
	```rust
	#[derive(Clone, Debug, Deserialize, Serialize)]
	#[serde(untagged)]
	pub enum LocationItem {
	    Variant0(String),
	    Variant1(i64),
	}
	```
	- enums with newtypes seems to behave better, so maybe there is a chance to do this by improving the types on the python side:
	```json
	"loc": {
	"anyOf": [ 
		{ "$ref": "#/components/schemas/PackageGroup" },
		{ "$ref": "#/components/schemas/PackageDescriptor" }],
	},
	```
	
	```rust
	#[derive(Clone, Debug, Deserialize, Serialize)]
	#[serde(untagged)]
	pub enum LocationItem {
		Group(PackageGroup),
    	Descriptor(Box<PackageDescriptor>),
	}
	```
- generates relevant `From` and `FromStr` implementations

### Client

- simple enough implementation, all connection details (i.e. auth) are handled by the wrapped `reqwest::Client`
```rust 
pub struct Client {
    pub(crate) baseurl: String,
    pub(crate) client: reqwest::Client,
}
```

- **only generates async code** -- not necessarily surprising but something to consider given our aim to deasyncify
- api results return custom wrappers by from the `progenitor_client` library which parse responses into somewhat sensible types.

# General remarks on the spec

* manually amending a generated spec seems error prone to me tbh 
	- i have not followed up on what were the difficulties on the fastAPI side to generate a 3.0.* spec so, no idea what is the complexity there
	- personally i start thinking that "an implementation as the source of truth for a spec" is a bit backwards. We now start to make changes to server implementation in order to nudge the spec in a way that we _can_ generate a client out of it. A single spec that generates both client and server appears more natural as it avoids conflating "how components talk to each other" with "how is the content produced and processed", even if it means we'll have integration work on both ends as the spec changes.
* anyOf with primitive types produce ugly enums
	- can/should we define types?
* `search_api_v1_catalog_search_get`'s `catalog` argument takes a string, that is a comma separated list of catalogs. Would a it make sense for this to be a POST request instead and use an a json request body instead?

**Comment by ysndr** [comment]
possibly relevant progenitor issues:

- specifying certain types or format restrictions on fields seem to cause panics
	- https://github.com/oxidecomputer/progenitor/issues/106
- issues with duplicate/conflicting names for nullable fields:
	- https://github.com/oxidecomputer/progenitor/issues/66
	- https://github.com/oxidecomputer/progenitor/issues/398
- nullable and non required:
	- https://github.com/oxidecomputer/progenitor/issues/286 	 	
- maybe `query` is a reserved word (possibly relevant for search)?
	- https://github.com/oxidecomputer/progenitor/issues/717
- openapi 3.1.0 is not supported
	- https://github.com/oxidecomputer/progenitor/issues/762

**Comment by mkenigs** [comment]
Outcome was https://github.com/flox/flox/issues/1271
