### ISSUE TITLE
Update Rust toolchain

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1302]
I'm not sure what the best approach will be, but do one of:
- bump nixpkgs
- use fenix
- use rust-overlay
- something else

Such that we have a rustc higher than 1.73

Timebox to a 2

Ideally we choose something that we can easily bump every 6 weeks so we can follow the Rust release cadence.

**Comment by zmitchell** [comment]
I changed the title to reflect the entire Rust toolchain since `rustc`, `cargo`, etc need to all be updated together.

Using `rust-overlay` or `fenix` you can set the toolchain to `stable`, which will automatically update to the latest stable toolchain (that those packages know about) whenever the flake lock is updated. @ysndr said that `fenix` is more common now, which is fine by me. `fenix` also has an example of how to use it with `crane`, which we currently use to build `flox`, so integration doesn't sound difficult.
