### ISSUE TITLE
Customize new version notification based on user's platform

### ISSUE THREAD

**Issue by jennymahmoudi** [flox/flox#1304]
As a followup to #1204, let's improve the notification by providing platform-specific upgrade instructions/links.

- Detect the user's platform
- Change the docs anchor link for macos from https://flox.dev/docs/install-flox/#__tabbed_1_3 to **https://flox.dev/docs/install-flox/#macos** 
- Provide specific upgrade command or link
- Always show the first line of the notification
``` 
🚀  Flox has a new version available. {old_version} -> {new_version}
```

- And then the specific message for the platform:

#### Debian
```
Get the latest with:
  sudo apt update
  sudo apt --only-upgrade install flox
```

#### RPM
```
Get the latest with 'sudo yum update flox'
```

#### macOS
```
Get the latest at https://flox.dev/docs/install-flox/#macos
```

#### All other (Nix, WSL)
```
Get the latest at https://flox.dev/docs/install-flox/#upgrade-existing-flox-installation
```

**Comment by mkenigs** [comment]
I would also suggest we link directly to the relevant instructions for macOS. Currently that would be https://flox.dev/docs/install-flox/#__tabbed_1_3, so I think we should change that from __tabbed_1_3 -> macos and link https://flox.dev/docs/install-flox/#macos

**Comment by crismxiex** [comment]
Hi, is this issue open for contribution?

**Comment by mkenigs** [comment]
Yep! You can ping on [our Slack](https://go.flox.dev/slack) if you have any questions. 

>     * Change the docs anchor link for macos from https://flox.dev/docs/install-flox/#__tabbed_1_3 to **https://flox.dev/docs/install-flox/#macos**

We'll have to do this part internally

**Comment by garbas** [comment]
Hey! When working on the homebrew cask I've noticed that upgrade based on platform detection would not be enough. A platform can have many ways how to get flox.

A simple example is macOS where we don't know how flox was installed by `brew` or directly by downloading `.pkg` installer. We need to "record" this at installation time.

For this reason I've created #1557 PR which reads upgrade instruction from a predetermined location. It also makes sense that installer codebase is responsible how to upgrade flox since it has the responsibility to install it in the first place.

@crismxiex I'm sorry to steal this ticket from you, but I was just recently pointed out that somebody else was working on this issue as well.
