### ISSUE TITLE
`flox init` finds alternate naming of `requirements.txt`

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1323]
## Acceptance Criteria

**Given** my python requirements are saved as `requirements_versions.txt` in the root of my project directory
**When** I `flox init`
**Then** Flox detects python requirements and displays suggestions

## Original Issue

The file being named `requirements.txt` is, I believe, a convention and not an, er, **requirement**. You need to provide the filename to `pip` explicitly, there is no default. In several of the Stable Diffusion projects I encountered, it's actually called `requirements_versions.txt`. As best as I can tell, the reason for the alternate name can be traced back to a completely different project that wanted to keep separate lists for different versions of Python.

I do not see this as a defect in the project; they're free to name it whatever they like.

But in this case, it seems like we could have an opinion that `requirements*.txt` also matches, with preference for the shortest matching filename.

STR:
```
git clone git@github.com:runew0lf/RuinedFooocus.git
cd RuinedFooocus
flox init
```

Expected result: `flox init` sees `requirements_versions.txt` and creates the virtual environment as normal.

Workaround: `ln -s requirements_versions.txt requirements.txt` and rerun `flox init`, but this is not ideal.

**Comment by crsche** [comment]
Hey @ghudgins, could I give this a shot?

Also, since you mentioned that Python requirements files can be named anything and are explicitly specified by the user when using `pip`, is it a good idea for `flox` to have the same behavior—a way of explicitly providing a Python requirements file (assuming there isn't one already)?

**Comment by ghudgins** [comment]
Yes. I suppose the hard part here is how we will find the right .txt file. The suggestion i'm talking about is a convenience thing so I wouldn't want a user to have to pass in anything...just for `flox init` to find the requirements.txt somehow. 

If I were to try to solve this I would imagine it would involve some sort of regular expression (just an idea, i'm a bad engineer at my core) looking for all lines of the file to have.... `==` in it? Then look through all `.txt` files in the current directory for this pattern and use the first one you find. CC @rossturk if he has any ideas since I pasted his original issue into this ticket

**Comment by ghudgins** [comment]
@crsche it's all yours! just don't forget to sign the CLA as part of the CONTRIBUTING guide. let us know how we can help

**Comment by crsche** [comment]
> If I were to try to solve this I would imagine it would involve some sort of regular expression (just an idea, i'm a bad engineer at my core) looking for all lines of the file to have.... `==` in it? Then look through all `.txt` files in the current directory for this pattern and use the first one you find in the suggestion. The suggestion itself would need to modify the script flox generates so it uses the same file name detected `pip install -r \"$FLOX_ENV_PROJECT/requirements.txt\" --quiet`

This makes sense, but it seems like the  **accepted** structure of `requirements.txt` is significantly more complicated than what's common (lines of `dep_name==0.0.1`) . See [this spec](https://pip.pypa.io/en/stable/reference/requirements-file-format/) for more details. 

Also, it seems like there's no easy way to determine the "root" `requirements` file since `pip` supports [references to other requirements files](https://pip.pypa.io/en/stable/reference/requirements-file-format/#referring-to-other-requirements-files) that would make regex matching even more difficult. 

I think the best approach would be to match filenames (`requirements*.txt`) like you mentioned in your first comment—not a perfect approach, but I think it would cover the majority of use cases like `requirements_versions.txt` (feel free to correct me though, I'm not too familiar with Python conventions/projects).

**Comment by ghudgins** [comment]
sounds good to me!

**Comment by mkenigs** [comment]
@crsche feel free to ping on Slack if you have questions https://go.flox.dev/slack

**Comment by crsche** [comment]
In writing unit tests for the modified `Requirements::detect()`, is it alright if I use [`tempfile`](https://docs.rs/tempfile/latest/tempfile/), or does `flox` do fs-oriented testing differently?

**Comment by mkenigs** [comment]
We use `tempfile` a good bit in tests

**Comment by zmitchell** [comment]
I think we want to do more than just take one `requirements*.txt` file. It's pretty common to have a `requirements.txt` and a `requirements_dev.txt`. In that case we'd want to detect all of them an potentially install all sets of requirements.

**Comment by crsche** [comment]
Just updated to install from all matching requirements files, feel free to take a look.

**Comment by rossturk** [comment]
> I think we want to do more than just take one `requirements*.txt` file. It's pretty common to have a `requirements.txt` and a `requirements_dev.txt`. In that case we'd want to detect all of them an potentially install all sets of requirements.

In that case, yes. You'd want to install the union of packages across both. But in the case I encountered, I believe you'd choose one depending on whether you want versions pinned or not.

I'm +1 on assuming the union for now - should we find out that it's a bad assumption we can adjust.
