### ISSUE TITLE
`flox upgrade` using catalog

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1361]
All behind a feature flag...
- Lock an environment's manifest using the `/resolve` endpoint instead of `pkgdb`. This is essentially the same as locking, except all package descriptors are unlocked
- Add 1 functional test for `flox upgrade`

**Comment by ysndr** [comment]
impl sketch:

```rust
        let client: catalog::Client = flox
            .catalog_client
            .ok_or(CoreEnvironmentError::CatalogClientMissing)?;

        let manifest: TypedManifestCatalog = toml::from_str(&self.manifest_content()?)
            .map_err(CoreEnvironmentError::DeserializeManifest)?;

        let lockfile_path = CanonicalPath::new(self.lockfile_path())
            .map_err(CoreEnvironmentError::BadLockfilePath)?;

        let current_lockfile = LockedManifest::read_from_file(&lockfile_path)
            .map_err(CoreEnvironmentError::LockedManifest)?;

        let upgraded_lockfile = LockedManifestCatalog::lock_manifest(&manifest, None, &client).await
            .map_err(CoreEnvironmentError::UpgradeFailedCatalog)?;

        /// TODO: Not sure what the pkgdb upgrade returned but (eventually)
        ///       this is the opportunity to return a diff of the upgraded packages
        let upgraded_packages = ???;

        let store_path = self.transact_with_lockfile_contents(serde_json::to_string_pretty(&upgraded_lockfile).map_err(CoreEnvironmentError::SerializeLockfile), flox)?;
        
        Ok(UpgradeResult {
            packages: upgraded_packages,
            store_path: Some(store_path),
        });

```

**Comment by ysndr** [comment]
Since `CoreEnvironment::lock`ing is getting more expensive now with the migration to a service, we may need to reconsider whether `CoreEnvironment::build` should implicitly lock at all. I.e. for `upgrade` resolve requests are made, where the second one will be fully locked already.
Using pkgdb this is a relatively minor cost as all _real_ work is skipped. In a service implementation we pay with network time even if the resolution itself is almost a noop.

Aside, currently `CoreEnvironment::lock` also does not verify the locked result by building it (since building implies a recursive call to locking) which could be addressed at the same time.

**Comment by mkenigs** [comment]
>     * Add 1 functional test for `flox upgrade`

I originally meant we should have 1 test that actually hits the catalog - I still think that's probably worth having?

**Comment by ysndr** [comment]
Yeah we I guess that works, when I started with this I think the upstream server had some issues. Once that's all available let's move them (considering that we'll make catalog enabled integration tests over the next few weeks anyway)

**Comment by ysndr** [comment]
Is translating this to a functional test blocked on upstream changes as well like #1359?
