### ISSUE TITLE
set catalog feature flag for integration tests (activate)

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1419]
- Copy any tests in `activate.bats` that are impacted by the catalog and run them with the catalog feature flag set. Make any small changes required to get them passing
- Set `FLOX_FEATURES_USE_CATALOG=true` and  `_FLOX_USE_CATALOG_MOCK=/dev/null` for all other tests in the file
- If anything that isn't minor breaks, skip copied tests and create followup tickets

**Comment by ghudgins** [comment]
if it's low effort to port to unit tests, we should in scope of this issue

**Comment by zmitchell** [comment]
Notes:
- Several tests install packages to an environment, so you'll need mock data for that series of responses to the `/resolve` endpoint. It looks like most of them just install `hello` so you won't need much.
- Every test calls `init`. You probably want a constant that contains any mock `init` data, populate the environment variable with this data in `project_setup` since we `init` in `project_setup`. The constant lets you `init` in test bodies as well since some of them `flox delete; flox init`.
- Several of these unit tests `init` during `project_setup` and then immediately `delete` and `init` in the test body. It's probably worth only doing an `init` when necessary for test times.

**Comment by mkenigs** [comment]
We're merging some more tests that use install in https://github.com/flox/flox/pull/1467, but the `flox install` can probably just be dropped, see https://github.com/flox/flox/pull/1467#discussion_r1609028082

**Comment by limeytexan** [comment]
> We're merging some more tests that use install in #1467, but the `flox install` can probably just be dropped, see [#1467 (comment)](https://github.com/flox/flox/pull/1467#discussion_r1609028082)

Added patch to fix this in #1475
