### ISSUE TITLE
Migrate v0 manifest and lockfile to v1

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1466]
If the catalog feature flag is set:
- At the start of any transaction with a pre-existing v0 manifest, try to convert to v1. Error if that's not possible and say what field is no longer supported
- At the start of any transaction with a pre-existing v0 lockfile
    - If non-interactive, error and say a `flox upgrade` is necessary
    - If interactive, ask if it's okay to perform an upgrade. Perform the upgrade. Then start the actual transaction
- If both manifest and lockfile are v0, both migrations should occur in a single transaction. If we define how that works a bit more clearly, we could maybe split this into a manifest ticket and a lockfile ticket

**Comment by zmitchell** [comment]
- Transactions happen in the `sdk` layer, but we need the ability to prompt the user as well
- I think we should do this **check** before doing the transaction because it will save us making extra copies of the environment directory just to find out the versions are different. Maybe a new method on the `Environment` trait just to keep the logic all in one place.

**Comment by zmitchell** [comment]
- Might need to handle `=` for package versions

**Comment by mkenigs** [comment]
We now error for v0 locks and decided we don't need to migrate since these cases are niche enough
