### ISSUE TITLE
improve install resolution error message

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1482]
### Motivation

**When** I put two packages that can't be found in the same catalog 'page' (nixpkgs revision)
**I need** a better message telling me what to do about it
**So I can** resolve the issue without having to think about Flox's subsystems

Today's error:

```
❌ ERROR: Failed to lock the manifest.

resolution failed: status: 406 Not Acceptable; headers: {"server": "nginx", "date": "Thu, 23 May 2024 12:07:30 GMT", "content-type": "application/json", "content-length": "55", "connection": "keep-alive"}; value: ErrorResponse { detail: "Unable to resolve package group 'toplevel'" }
```

### Acceptance Criteria

**Improve the error message when there is a pkg-group conflict**

**Given** I have `flox install nodejs@20.11.1`
**When** I flox install `flox install curl@8.7.1`
**Then** I see an error...

```
❌ ERROR: Failed to lock the manifest.
'toplevel' package group has conflicts. 

Use 'flox edit' to adjust version constraints in the [install] section  
or isolate dependencies in a new group with '<package>.pkg-group = "newgroup"' 

```

**Don't regress system specific errors**

**Given** I am on darwin
**When** I `flox install virtualbox`
**Then** I see 
```
❌ ERROR: package 'virtualbox' is not available for this system ('aarch64-darwin'), but it is available on 'x86_64-linux' and 'aarch64-linux'.

For more on managing system-specific packages, visit the documentation:
https://flox.dev/docs/tutorials/multi-arch-environments/#handling-unsupported-packages
```

**Don't regress package does not exist error**

**When** I `flox install blahblah`
**Then** I see
```
❌ ERROR: Could not find package blahblah. Try 'flox search' with a broader search term.
```

**Don't regress suggestions**

**When** I `flox install node`
**Then** I see

```
❌ ERROR: Could not find package node.
Try 'flox install nodejs' instead.

Here are a few other similar options:
  $ flox install nodejs
  $ flox install elmPackages.nodejs
  $ flox install nodePackages.nodejs
...or see up to 30 options with 'flox search nodejs'
```

**Comment by ghudgins** [comment]
@jennymahmoudi (or anyone) could use some help on the wording

**Comment by ghudgins** [comment]
depends on https://github.com/flox/catalog-server/issues/62

**Comment by mkenigs** [comment]
I think the message should be a little bit less confusing for the simple typo case. Currently we have:
```
flox install helloz
❌ ERROR: Could not find package helloz.
```

At some point we'll want to differentiate between packages that don't exist and packages which have too strict a version constraint, but for now we just need to choose a catch-all

**Comment by ghudgins** [comment]
I was hoping we could catch the locking error specifically for this:

>detail: "Unable to resolve package group 'toplevel'"

**Comment by billlevine** [comment]
I could try to do a trivial 'gathering' of _reason_ messages during resolution and add them to the failure response.
Package `foo` not found.
Page <rev>, package <foo>, failed version check:
Etc...
But there could be a lot of them, especially for upgrades where there will be a lot of derivation mismatches before it attempts with the derivations unlocked.  And the fancier we get the more time it will take.  But maybe that's worth a first go, and they can be shown with a `-vvvv` flag.  Can't be much worse then some of the HTTP exceptions we're getting.
The CLI could eventually parse them to make better sense of them.

**Comment by zmitchell** [comment]
I'd rather us at least have those two different cases.

If I do this:
- `flox install foo`
- `flox show bar` -> see version `x.y.z`
- `flox install bar@x.y.z` -> error
I'm going to think the software is broken.

**Comment by ghudgins** [comment]
>But maybe that's worth a first go

more information to help you sort out this doesn't seem like a bad first blush

can you write down what you have in mind from the user's perspective? We could also show first N and offer the user the `-vvv`'s (I know i'm in idea land adding scope but thought i'd mention it--could be a follow-on)

**Comment by billlevine** [comment]
Perhaps something like the following.  I would like to get the data model about right as there is more impact in changing that.  But if we have generally useful and flexible fields for the purpose of explaining the resolution process, the exact text can be improved on, both server side and client side.  I think it needs to be a mix of client and server messaging, since trying to convey every resolution issue via explicitly modeled data will be an ongoing struggle.

We need a data model to return both unresolved and resolved pages as well as a list of messages.
We could add a flag on each catalog page if it is a valid candidate or not (all constraints met). And add a list of messages for each page that can list the logic for that page.

For a given page and package, the following messages could be provided directly from the current logic flow:
```
Package foo derivation XXX does not match YYYY.
Package foo's derivation constraint removed to attempt looser resolution.
Package foo version A.B.C does not meet the version constraint >=D.*
```
So this would explain if an older page was selected when installing something new, showing that the derivations on newer pages was not the same and so those pages were excluded.  If we fail to resolve with the derivation constraint, the logic checks every page again, ignoring derivation, but checking the version, and so the second message would be added for that page.  That could also be used as a warning to the user IFF we wanted to tell the user that happened.

If a page does not include any derivation of one or more packages in the group, it could have a single message for the page:

```
Page 60000 does not include derivations for packages foo,bar.
```

This could look something like the following data model.  This is flexible in that we can include other messages as we see a need, other message classes, etc.  There is a single list of messages per group, but they could include the install-id to in order to collect them for presentation to the user, or processed otherwise.  The `resolved` bool is added so we can return pages that do not resolve as well as ones that do with the explanation.  It could all be gated by a query parameter to enable the _vebose_ mode if we wanted.

```
+class MessageClass(str, Enum):
+    INFO = "info"
+    ERROR = "error"
+
+class ResolutionMessage(BaseModel):
+    # The class of message
+    msg_class: MessageClass
+    # The actual message text
+    message: str
+    # The corresponding install_id to which this message relates
+    install_id: str
+
 class ResolvedPackageGroup(BaseModel):
     class CatalogPage(BaseModel):
         page: int
         url: str
         packages: Optional[list[ResolvedPackageDescriptor]] = None
+        messages: Optional[list[ResolutionMessage]] = None
+        resolved: bool
         model_config = ConfigDict(json_schema_extra={"examples": [_PackageInfo_Ex1]})  # type: ignore[list-item]

...
```

**Comment by billlevine** [comment]
To clarify, what I suggested is more `-vvv` worthy if it's ever exposed to the user at all.  My intent was to provide enough useful info to the CLI to determine a useful concise error to show the user in summary and the level of detail provided here was probably misplaced and can be kept on the catalog tickets as to how this info gets represented.

I think the two cases could present as follows.  I think perhaps an explicit option to `explain` the resolution would be better then `-vvv` that would also spew a lot of other info.  It could be included in just `-v` but the volume of output could be significant and could obscure other info the user may want to see.  I feel like the second message is getting a little long, so perhaps we don't need to put that there and having it in help and the docs is sufficient?
```
flox install helloz
❌ ERROR: Could not find package helloz.
```
and 
```
❌ ERROR: Failed to lock the manifest.
'toplevel' pkg-group has conflicts. 

Resolve this by loosening or adjusting version constraints of software 
or isolating dependencies to their own pkg-group with 'flox edit'.
Use `--explain-resolution` for a detailed explanation.
```

**Comment by jennymahmoudi** [comment]
I would rather see "package group" when talking about what it is, and "pkg-group" when talking about how to implement it. 

Edited to be more direct and explicit with how to do the things we're suggesting. Otherwise, I'd want to link to docs here and that feels like overkill if we can give them the tl;dr. 
 
```
❌ ERROR: Failed to lock the manifest.
'toplevel' package group has conflicts. 

Use 'flox edit' to adjust version constraints in the [install] section  
or isolate dependencies in a new group with '<package>.pkg-group = "newgroup"' 
```

**Comment by ghudgins** [comment]
+1'd from @rossturk

**Comment by ghudgins** [comment]
there's a regression in the system error:

without feature flag (today)
```
$ flox install virtualbox
❌ ERROR: package 'virtualbox' is not available for this system ('aarch64-darwin')

For more on managing system-specific packages, visit the documentation:
https://flox.dev/docs/tutorials/multi-arch-environments/#handling-unsupported-packages
```

with feature flag for catalog 
```
grahams-floxmac:flox ghudgins$ flox install virtualbox
❌ ERROR: Failed to lock the manifest.

resolution failed: status: 406 Not Acceptable; headers: {"server": "nginx", "date": "Tue, 28 May 2024 21:14:13 GMT", "content-type": "application/json", "content-length": "55", "connection": "keep-alive"}; value: ErrorResponse { detail: "Unable to resolve package group 'toplevel'" }
```

can I add a 3rd AC to preserve today's behavior?

**Comment by mkenigs** [comment]
Updated the AC to not regress suggestions

**Comment by mkenigs** [comment]
> @mkenigs FYI search suggestions is also in this issue - #1483

Yep I think we can adress install suggestions in this one, and search suggestions in 1483

**Comment by zmitchell** [comment]
- There will be comments per page and per group
- The messages should be treated as fallbacks, there should be enough type-level information to determine the resolution error
- "package doesn't exist" -> can be determined from `InvalidAttrPath` and an empty list of systems
- "package doesn't exist on this system" -> same thing
- "constraints couldn't be satisfied" -> will be in the group message
