### ISSUE TITLE
feat: fork "watchdog" process for shepherding flox activations

### ISSUE THREAD

**Issue by limeytexan** [flox/flox#1500]
There are several reasons we need a process to monitor the lifetime of an environment's activation, but the first of these came with #1299 as we created temporary files for replaying the environment variable manipulations associated with the activation. The basic idea is for flox to fork the "watchdog" process prior to exec'ing the `activate` script so that it can simply await the death of its parent before removing the tempfile, but there are other things we can do with this approach, such as:

* submit metrics at the conclusion of an activation for reporting success, duration, etc.
* perform an ordering Sentry shutdown
* orchestrate service management
* provide centralised monitoring of active environments, status reporting

A sketch of the overall idea is included below and provides a detailed depiction of the activate process and a general notion of the operation of the watchdog process. A POC implementation of the "child and waits for death of parent" idea is available in PR #1516.

```mermaid
flowchart TB
 subgraph subgraph_p67vwuh5h["Activation PID"]
        node_glmdmumem["flox"]
        no{"--turbo\ncmd mode?"}
        nu{"--no-profile\ncmd mode?"}
        n9(["exec cmd"])
        n8(["exec cmd"])
        n4[["Initialize state\n(create temp files, etc.)"]]
        nb[["fork()"]]
        n3[["exec(bash activate)"]]
        n7[["source hook.on-activate"]]
        nq[["exec userShell"]]
        n5[["source profile.*"]]
        nm{"cmd mode?"}
        nx(["exec cmd"])
        ng(["interactive"])
  end
 subgraph subgraph_ru7zjclbt["Watchdog PID"]
        ns[["Await death of ppid()"]]
        ny[["Clean up state\n(remove temp files, etc.)"]]
        nv[["Rust Destructors\n(Submit metrics, Sentry, etc.)"]]
  end
 subgraph subgraph_7x7san49a["Color Key"]
        node_aqepkktvr["flox CLI\n(rust)"]
        n0["bash"]
        nz["userShell"]
  end
    no -- no --> nq
    no -- yes --> n9
    nu -- yes --> n8
    nu -- no --> n5
    A(["Parent shell"]) -- fork() && exec(flox) --> node_glmdmumem
    node_glmdmumem --> n4
    ns --> ny
    ny --> nv
    n4 --> nb
    nb -- parent --> n3
    n7 --> no
    nq --> nu
    n5 --> nm
    nm -- yes --> nx
    nm -- no --> ng
    n3 --> n7
    nv ~~~ subgraph_7x7san49a
    nb -- child --> ns
    node_aqepkktvr --> n0
    n0 --> nz
    style node_glmdmumem fill:#FFE0B2
    style no fill:#BBDEFB
    style nu fill:#E1BEE7
    style n9 fill:#BBDEFB
    style n8 fill:#E1BEE7
    style n4 fill:#FFE0B2
    style nb fill:#FFE0B2
    style n3 fill:#FFE0B2
    style n7 fill:#BBDEFB
    style nq fill:#BBDEFB
    style n5 fill:#E1BEE7
    style nm fill:#E1BEE7
    style nx fill:#E1BEE7
    style ng fill:#E1BEE7
    style ns fill:#FFE0B2
    style ny fill:#FFE0B2
    style nv fill:#FFE0B2
    style node_aqepkktvr fill:#FFE0B2
    style n0 fill:#BBDEFB
    style nz fill:#E1BEE7

```

## Acceptance criteria

* successfully reporting metrics following flox activations, including the total duration of those activations
* relocate the environment variable addition/deletion files out of /tmp and remove them as part of the environment teardown logic

**Comment by limeytexan** [comment]
TODO: will update ...
* pseudo code Description of Linux and MacOS implementation of wait_parent_pid() and citations of where I found it
* test cases
* ... instrumentation ... leave for implementer
* PR1516 already linked ...

**Comment by zmitchell** [comment]
Also a problem:
```
    //     $ flox activate -d /tmp/asdlkfjasdlkfj -- sleep 3
    //     thread 'main' panicked at /Users/brantley/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/io/driver.rs:209:27:
    //     failed to wake I/O driver: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }
    //     note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by zmitchell** [comment]
We discussed maybe starting the watchdog in `main` before starting the `tokio` runtime to avoid this `tokio` forking issue, but I just remembered that you also need the runtime around in order to start Sentry, so we'll probably need a different workaround.

**Comment by zmitchell** [comment]
Discussed in the CLI meeting today.

Requirements for first go at a watchdog:
- The watchdog is created before calling `exec` in `flox activate`
- The watchdog waits for a process to terminate (the shell that's been `exec`ed in normal operation)
- Once that process terminates, the watchdog uses the `process-compose` socket to tell `process-compose` to terminate the running services.
- The watchdog exits.

We also discussed making the watchdog a separate binary for the following reasons:
- Doesn't add more functionality to `flox` itself.
- Allows the watchdog process to be created and configured on its own e.g. send it a signal directly rather than waiting for the parent process to die. I mentioned in the meeting that we can configure the watchdog to wait for a particular PID to terminate, but you can apparently only do this on macOS.
- Allows easier testing (launch the watchdog directly rather than needing to call `flox activate`).

We also decided to call the watchdog `klaus`.

**Comment by zmitchell** [comment]
Last few breakdown things:
- Starting the watchdog process so that it won't get killed when the shell exits is done via `Command::spawn`. 
- We also need to call `setsid` during `pre_exec` so that the watchdog is put into a new process group and detached from the terminal. When you press Ctrl-C the terminal intercepts this character and sends the  SIGINT signal to all of the processes in the foreground process group. The activation is likely in the foreground process group (and likely its leader), and when the watchdog is spawned it will inherit this process group. Therefore we need to separate the watchdog from this process group and terminal so that Ctrl-C (and other job control commands) don't interfere with the operation of the watchdog
- The watchdog process should accept command line arguments for configuration during testing (location of the socket, location of the environment registry, etc). On Linux the process whose termination triggers watchdog actions isn't configurable (it's always the parent), so this option can either be a no-op or an error on Linux.

**Comment by zmitchell** [comment]
- Watchdog binary needs to be built and included in installer.
