### ISSUE TITLE
Strip version from search term

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1506]
~Once changes to search behavior are made serverside, `flox search pkg@version` should populate the `version` field in the request sent to the server.~

- In comments for `flox search --help` marked with
  ```
  // TODO: catalog release:
  ```
  remove all mention of searching with version.

- Copy the man page for search to `catalog-doc` and remove any mention of version.

- Drop skipped catalog semver tests in search.bats

- If a search term provided by the user ends with a `@` or `@XXX`, strip it from the term sent to the server
- (nice to have) print this message to the user (as a warning not an error):
  ```
  ⚠️ 'flox search' ignores version specifiers. 
  To see available versions of a package, use 'flox show'
  ```

**Comment by zmitchell** [comment]
@ghudgins could you provide some context for this. Is this something we want for catalog simply because we have it for `pkgb`, or is it solving a user problem that isn't covered by e.g. `show`?

**Comment by billlevine** [comment]
As per our discussion regarding flox/catalog-server#60, we will not support filtering on version at this time.  Since this is a currently supported syntax, the CLI should strip off the version constraint `@<>` before sending the search term to the catalog service.  It could also append a message, perhaps conditionally based on if a version was added to the search term by the user.

This will have to be implemented for search to continue _working_ as it has in the past.

**Comment by mkenigs** [comment]
Updated description accordingly
