### ISSUE TITLE
Add `licenses`, `unfree`, and `broken` to resolution responses and process in flox-cli

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1507]
Resolution requests should be populated with the values for `licenses`, `unfree`, and `broken` found in the manifest.

We need to port the logic that warns when unfree packages are installed, see https://github.com/flox/flox/blob/cdc0835aa5e6cc61f14f8de16cf467be960b88e5/pkgdb/src/resolver/lockfile.cc#L334

Add test cases to verify `broken` and `unfree` packages can be built if we don't already have them.

**Comment by dcarley** [comment]
Notes for refinement:

- I believe that https://github.com/flox/catalog-server/pull/78 hasn't been deployed to preview yet and is batched with some other changes
- The unhappy path of failing to resolve a suitable package is being handled in https://github.com/flox/flox/issues/1482
- Are the test cases intended to be integration/functional tests so that we do the complete build/install?
- Is there a good example of a `broken` package that can be built?
- Otherwise it mostly seems like plumbing the same as we currently do for `allow_pre_releases`

**Comment by mkenigs** [comment]
Need to unskip one test for broken once broken is available serverside but I'll do that as followup
