### ISSUE TITLE
Catalog resolution doesn't error when response contains different packages than requested

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1522]
In a request to install hello, success is reported even when the response only contains emacs:
```
> _FLOX_USE_CATALOG_MOCK=./cli/tests/catalog_responses/resolve/emacs.json FLOX_FEATURES_USE_CATALOG=true flox install hello
✅ 'hello' installed to environment 'main'
```

This should be an error. We would only run into this when hacking on tests or if there's a bug serverside.

**Comment by ysndr** [comment]
Similarly, empty responses are always accepted.

Since we are now creating a catalog descriptor for every package x system, it would be easy to check the response against the requested packages before adding them to the lockfile somewhere around here:
https://github.com/flox/flox/blob/6474bf7ea433d3ec19fb4725ed51662e26ba489d/cli/flox-rust-sdk/src/models/lockfile.rs#L328-L336

**Comment by ysndr** [comment]
likely this can be combined with efforts on https://github.com/flox/flox/issues/1507

**Comment by mkenigs** [comment]
Closing in favor of https://github.com/flox/flox/issues/1659
