### ISSUE TITLE
catalog: flox install vim@8.2.2567 fails with "package group had no page"

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1545]
STR:
* i'm on aarch64-darwin if it matters
* enable catalog feature (not yet released)
* `flox init`
* `flox install vim@8.2.2567`

Result: `❌ ERROR: resolution failed: package group had no page`

Expected: success (or don't show this as an option in `flox show vim`) or some other solution

**Comment by billlevine** [comment]
This is b/c we default to all 4 systems, and that version is missing for `aarch64_darwin`.  Unfortunately, since that package exists for that system on other pages with other versions, the only message you'll get right now will be that `the constraints are too tight` which is at best not too helpful, at worst could be misleading (the only constraint specified by the user was version).

**Comment by ghudgins** [comment]
we discussed, this should be resolved by https://github.com/flox/flox/issues/1499

**Comment by zmitchell** [comment]
Can we close this?

**Comment by ghudgins** [comment]
yes 🎉
