### ISSUE TITLE
Use watchdog to stop services

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#1588]
After:
- https://github.com/flox/flox/issues/1770

When the watchdog is notified that the parent process has terminated, it should
- ~~Remove the watchdog's PID from the environment registry (done)~~
- If it was the last entry and the `process-compose` socket exists
  - Tell process-compose to shut down the running services

**Comment by zmitchell** [comment]
Breakdown:
- The watchdog either needs to be initialized with the socket path, or it needs to be able to look it up (also potentially in the registry). The watchdog could use the `Environment` methods to get the socket path, but it would be better if the watchdog didn't need to initialize an `*Environment` just to get that path. The `_FLOX_SERVICES_SOCKET` variable isn't set yet (it's set on the activation, and the watchdog is launched before that's `exec`ed). I think it makes sense to pass to `klaus` as an argument.
- If `process-compose` isn't running when the watchdog goes to clean it up, should it just error silently?

**Comment by dcarley** [comment]
- deregistation of activation PIDs is already implemented
- we're now always passing the socket path to the watchdog and we can check for the existence of the file to determine whether we need to shutdown `process-compose`, to allow for cases where https://github.com/flox/flox/issues/1591 starts `process-compose` after the activation/watchdog
- we should (re)consider whether we want to check for the last activation and stop `process-compose` when the watchdog exits early due to the parent activation no longer being available.
