### ISSUE TITLE
View service logs (recent, one shot)

### ISSUE THREAD

**Issue by dcarley** [flox/flox#1589]
When within or outside an activation:
- ~`flox services logs` shows recent logs for all services~ 
- ~`flox services logs [name ...]` shows recent logs for the named services~
- `flox services logs name` shows recent logs for the named service
- the above command:
  - exit after showing the N most recent logs
  - ~interleave output from multiple services~
  - error if any of the named services don't exist
  - error if called within a remote environment

**Comment by ysndr** [comment]
triage notes:

> exit after showing the N most recent logs

~currentl`y (or last time i checked), process compose just blocks with no output once a process has finished

If the process logged less than N lines, flox would likewise block waiting for more lines to be printed~

apparently now it will actually stop, but print `write close: write unix ->test.sock: write: broken pipe` to stdout 🙃, at least that's parseable.
That seems to _also_ be the case now for follow logs, i.e. when the process stops it does not block anymore but log the above message.

This is actually a great development and should make implementing this issue easier.

* add `{ProcessComposeLogStream, ProcessComposeLogReader}::new_tail` to start processes with `-n` flag, we'd otherwise _not_ get the last N messages but the first N in the buffer.
	+ implementors choice to add a methods or argument or X

* add missing error handling for:
* 
> * ~error if any of the named services don't exist~ (implemented in #1897)
> * error if called within a remote environment
>
> * When not within in activation:
> an error is returned because we are only supporting services within activations for now.

Are these error cases the same for other commands as well?

**Comment by ysndr** [comment]
Actually, since we don't know the total order of log lines, with the current implementation we will receive up to `n` logs per process more or less _instantaniously_, i.e. with a tail of {1..N} and processes {1..M} we are very likely only printing logs {1..N} for a single process rather than "interleav[ing] output from multiple services".
Also running the command multiple times, even with all services stopped, will return different results.

Do we have plans how to approach this interleaving?
Possible options are:
- not doing anything, and risk logs for a majority of processes being underrepresented
- not allowing one shot logs for multiple processes
- fairly share the available N logs among  the processes, e.g. using some round-robin 
  `{(1, 1), (1,2), ... (1, M), ... (N, M)}[1..N]`
- Show N logs _per process_, i.e. print up to `M*N` lines.
- find or create a totally ordered log
	- process-compose's logfile perhaps, but still weird since that is cntinuously being written to and is rotated.
	- run `process-compose process logs <proc> -n 0 --follow` and collect up to N logs from all processes (combining `-n 0` and  `--follow` was not possible when the current logging was implemented, ie. before we upgraded process-compose).

**Comment by mkenigs** [comment]
>     * not allowing one shot logs for multiple processes

We'll do this per sync

**Comment by ysndr** [comment]
> When not within in activation 
> - an error is returned because we are only supporting services within activations for now.

With the watchdog and all is this still true?

#1858 suggests that the error cases are "there is no activation [at all] [...]" and "there is an activation [somewhere], without services started [...]".
Notably, it does not require you to _within_ that activation.
Considering that this issue was created on June 12 and #1858 last week, we should confirm or update this error case.
I'd prefer we are not adding sepecific error cases to individual commands unless necessary and defer the error messaging/handling to the impl of #1858 unless we want to pull the work now.

**Comment by dcarley** [comment]
> > When not within in activation
> > 
> > * an error is returned because we are only supporting services within activations for now.
> 
> With the watchdog and all is this still true?

Nope, that's out-of-date, sorry.

It's only `flox services start` that we don't support outside of an activation because we need an activation for a newly started `process-compose` to belong to. However, now that I think about it, we'll also have to do the same for https://github.com/flox/flox/issues/1594

I'll update the descriptions.
