### ISSUE TITLE
Migrate v0 manifests that get locked outside of transactions 

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1624]
There are a number of codepaths that lock an environment outside of a transaction: `activate`, ~~`containerize`~~, `list`, `push`, and `edit --sync`. If we're going to drop `pkgdb lock`, all of these need to first migrate a v0 manifest to a v1 manifest.

We should also only lock when necessary (it looks like `activation_path` may handle locking conditionally correctly). ~~`build_container` for example currently locks unconditionallyWe should be able to build a container given an already existing v0 lockfile. (no longer true after #1749)~~ . This will cause problems in dropping `pkgdb lock`.

It may make sense to move `lock` out of `ReadOnly`
https://github.com/flox/flox/blob/794f6b1ab48f9f2b5e78dec9942237af7e6eef53/cli/flox-rust-sdk/src/models/environment/core_environment.rs#L103-L105

**Comment by mkenigs** [comment]
Edited to include `edit --sync`

**Comment by ysndr** [comment]
Outside the environment methods we do not know whether we need to lock.
Thus when calling `Environment::activation_path` or `Environment::build`, etc. a error may be returned if a v0 manifest needs to be locked.

In these cases we can either

1. handle the error by prompting for a migration and then calling the environment methods a second time if the migration was successful

2. check whether we _will_ need to lock before calling other environment methods, prompt,  migrate and then run the respective environment method.


Why cant we add `maybe_migrate_to_v1` to activate and build_container unconditionally?
Neither has to lock if the lockfile is already there and current with the manifest.

Why cant we add `maybe_migrate_to_v1` to `edit --sync`?
Local changes would be mixed together with the migration.

-----

- Add error for attempted lock of v0 manifest
- remove all (integration) tests that lock v0 manifests (basically most non `catalog: ` tests)
	- excluding "upgrade" tests
	- and activation/containerize tests that only build existing lockfiles (may need to be adapted)
- Add a methods `CoreEnvironment::needs_lock() -> bool` that checks whether a  manifest _needs_ to be locked or if a lockfile for it already exists by checking the `manifest` attribute within the lockfile against the manifest contents.
- optimize CoreEnvironment::lock to return early if the environment does not need to be locked. In that case no error is returned either.
- add `maybe_migrate_to_v1` to `activate`, `containerize`, `push`, `list` conditional on `needs_lock`.
- `lock` existing manifest if necessary in `flox list` (https://github.com/flox/flox/issues/1710)

**Comment by ysndr** [comment]
@mkenigs i think there is another not spelled out componenet to this issue which is that there are commands that modify the lockfile without a transaction around it?
This is what i gather from the contexts of places where this issue was linked from so maybe you could expand on that too if that's what you had in mind.


should we consider implementing `Envrionment::lock` with a transaction in managed envs? Why would we do so considering that `lock` is an atomic operation (fs failures can also happen when committing a transaction so i would count those in just now).

I see how we can consider implementing `Environment::build` in a transaction since that is not atomic and while a locking of the env might succeed, a successive build of the new lockfile might not.

**Comment by mkenigs** [comment]
`lock` is confusing because it's read-write for `PathEnvironment`, but it's read-only almost by accident for `RemoteEnvironment` and doesn't create a new generation. So then we can't put manifest migration inside `lock`, because it can't create a new generation with the new manifest contents.

So I was saying "if we're going to perform manifest migration in lock, we'd need to create a new generation," but that's probably actually not what we should do, because I think a remote environment without a lock should be unreachable. So instead I think `RemoteEnvironment::lock` should try to read the lock, and if it doesn't exist error with `Corrupt environment`.

For `ManagedEnvironment`, if there's a local checkout with a v0 manifest, I guess we perform manifest migration and write it to the local checkout, but we don't `--sync`? If there's no local checkout and no lockfile in a generation, we can error with `Corrupt environment`.

If we do all that, we would want to move lock to `ReadWrite` because it could modify the manifest by performing a migration.

**Comment by zmitchell** [comment]
I think these suggestions make sense:
- For remote environments read the lock, error if it doesn't exist
- For managed environments, perform migration without `--sync` or error.

Can we not add a generation for the managed environment case and error for the remote environment? The fact that a user needs to `--sync` feels like a technical limitation more than something that's essential to the problem, which I don't feel great about.

For the managed environment case I think you need messaging for the user that the lockfile was modified during migration so they know they have a dirty environment that needs to be `--sync`ed. 

Off-topic, but I find the `--sync` flag a little confusing because it doesn't say which direction it's syncing, meta->checkout or checkout->meta. It's only unambiguous if you know that `--reset` exists and you assume that `--sync` must do something different from `--reset`.

**Comment by mkenigs** [comment]
> Can we not add a generation for the managed environment case and error for the remote environment? The fact that a user needs to `--sync` feels like a technical limitation more than something that's essential to the problem, which I don't feel great about.
> 
> For the managed environment case I think you need messaging for the user that the lockfile was modified during migration so they know they have a dirty environment that needs to be `--sync`ed.

I was thinking if there's already a local checkout, we migrate it. If there isn't a local checkout, we just error. That way there isn't a need for a message like "we just created a local checkout for you which you need to --sync"

**Comment by ysndr** [comment]
Would it work to have lock actually do a generation if necessary?
In remote envs that can be weird and we could error there (although lockless envs are a thing we want too and there we’d need to lock without committing. That’s an eventually though not a now.)

**Comment by mkenigs** [comment]
And if there isn't a local checkout, it should be unreachable for there to not be a lockfile, because we lock before we push

**Comment by zmitchell** [comment]
I think I'm also confused as to how/why you would be migrating a managed environment that doesn't have a checkout in your project

**Comment by mkenigs** [comment]
> Would it work to have lock actually do a generation if necessary?

Is there a case that makes sense?

Remote env: the env is corrupt if there isn't a lockfile
Managed env with no local checkout: the env is corrupt if there isn't a lockfile
Managed env with a local checkout: if you create a generation, you do an implicit `--sync` which is kinda weird. If you just migrate in place, the user is in a similar state to as before

**Comment by mkenigs** [comment]
Oh yeah `pull` can do an `edit_unsafe` which would create a new generation. In that case we should migrate and create a generation
