### ISSUE TITLE
flag to disable cuda detection in manifest

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1631]
### Motivation

**When** cuda support goes wrong
**I need** a way to turn it off
**So I can** avoid issues caused by cuda activation

### Acceptance Criteria

* An option exists in the manifest
* `options.cuda-detection` which can be set to false (true by default) that disables cuda activation
* new environments have `options.cuda-detection` in the template commented out with the comment that it's on by default
* man manifest.toml has doc about this mechanism

**Comment by dcarley** [comment]
Refinement notes:
- is passing down the existing `FLOX_FEATURES_ENV_ENABLE_CUDA` feature flag to `profile.d` the right interface between `flox` and `pkgdb`?
- if so, we could test that `FLOX_FEATURES_ENV_ENABLE_CUDA` is explicity disabled, and then create a separate ticket for CUDA testing infrastructure - which is important because only a subset of the team can manually test at the moment but it doesn't need to bloat/block this ticket

**Comment by ghudgins** [comment]
@tomberek can you add a few words about what this mechanism is doing for the man page?

**Comment by tomberek** [comment]
If trying to use CUDA libraries one has to ensure that the relevant and correct version of a host-provided libcuda.so can be loaded. 

The manifest option will detect if you have an Nvidia device by looking for `/dev/nvidia*` and attempt to locate the host-provided libcuda.so.1 in well-known locations. Then it will create symlinks pointing to them in `.flox/lib`, and set FLOX_ENV_LIB_DIRS to that folder.

Fundamentally, one of these must be done for flox-provided software to work with CUDA:

- symlink libraries into /run/opengl-driver/lib
- symlink located at $FLOX_ENV/lib pointing to host location, eg: /usr/lib/cuda, /usr/lib64, /opt/nvidia/random-place-user-might-have-put-it. And set FLOX_ENV_LIB_DIRS to this folder.
- point FLOX_ENV_LIB_DIRS to the right place directly to host libraries.

This same mechanism can be used to expose OpenGL drivers or other host-provided libraries in a way that is more likely to work than using LD_LIBRARY_PATH due to our mechanism of ensuring those libraries are loaded last, not first.

**Comment by ghudgins** [comment]
missing a few things I think given #1686 (unless i'm testing incorrectly, which is possible) 

1. would be good to add a line to the manifest template that comes out of flox init with this option commented out 2. manifest.toml doc edits

**Comment by ghudgins** [comment]
verified (at long last). I checked on WSL debian and two non-nvidia systems. once this merges and we have an installer from shipit i'll make sure everyone who has nvidia hardware re-verifies and will follow up with additional issues.

sorry for the rigamarole on the verification...something was up with my running main version!
