### ISSUE TITLE
Record watchdogs in environment registry

### ISSUE THREAD

**Issue by dcarley** [flox/flox#1770]
**Acceptance criteria**

When starting the watchdog from #1500 append (not replace) the activation PID to the environment registry.

Should use existing locking/mutex to prevent race conditions from multiple activations on the same environment.

Cleanup will be handled in #1588 (we can cope with them not being garbage collected in the meantime).

**Why**

This will allow us to clean up services when the last activation for an environment exits and supersedes the surprising behaviour from #1600 where the first activation with services owns the cleanup.

Eventually this behaviour could be delegated to a "Flox daemon" but that's out of scope for Service Management. For now we'll accept the risk on "JSON as a database", file locking, and shared state between watchdog versions ([private Slack thread](https://flox-dev.slack.com/archives/C06T9RL3BQT/p1720818187521009)).

Recording the activation PID, rather than the watchdog PID, will allow us to find the other children if we need to in the future.

**Comment by zmitchell** [comment]
Breakdown:
- We need to implement a basic amount of cleanup before doing #1588 otherwise we could have environment registries that have stale entries from activations between when this PR is merged and when #1588 is merged. It's likely only us who need to worry about that, but it means we'll likely need to do some manual work on our environment registries otherwise.
- Looking ahead: what if the watchdog crashes before it can remove its PID from the list? That could prevent cleanup from ever happening.
- Idea: every time a watchdog updates the environment registry, it tries to make sure it's fresh by getting the status of the PIDs in the list and removing any stale entries left behind by potential crashes.
    - Problem: These watchdogs aren't children of each other, so you can't use `waitpid`. You might also use `/proc`, but that doesn't exist on macOS. You're left doing a `kill(pid, 0)`, which returns -1 if the PID no longer exists (process has exited), or 0 if the process is still running _or_ if it's a zombie e.g. process has exited and parent hasn't cleaned it up or checked its status (e.g. called `wait*`). So a return value of 0 is ambiguous as to whether a process is still running or dead and waiting to be cleaned up.
        - I guess we could also parse the output of `ps` in a pinch. There's also the `libproc` crate, which on macOS uses bindings to `libproc.h`. That's an allegedly private API, so not entirely sure that's a great idea, but it might be less bad than parsing `ps` output.
- This will be one of the first real exercises of the environment registry.
- Conceptually it makes sense for the environment registry to be a separate crate shared between `flox-rust-sdk` and `klaus`, and the registry only appears to depend on `Flox` and `EnvironmentPointer` from `flox-rust-sdk`, but I'm not sure if it's worth the effort at the moment to figure that out.
- What should `klaus` do if the environment isn't in the registry? If this happens there is a bug in `flox`, but the watchdog will need to handle that situation.

**Comment by mkenigs** [comment]
Do we need to store the watchdog's PID, the activation's PID, or both?

**Comment by dcarley** [comment]
`kill(pid, 0)` seems like a reasonable start to guard against something that should rarely happen. Then we can add better safeguards (incl. checking the process name for re-used PIDs) and tests as we go, but just being able to clean-up `process-compose` and support "last activation out" would be a great first step.

I _think_ we can lookup the watchdog PID from the activation PID? But also it wouldn't hurt to store both and avoid a lookup.

**Comment by dcarley** [comment]
From conversation in service management meeting:
- removing the PID will need to be done from the watchdog so for symmetry it makes sense to do the adding from there too
- it will get the activation PID passed to it as a CLI arg
- it can still use the `flox-rust-sdk` crate, though technically the environment registry could be pulled out to a separate crate
- this ticket can be branched off https://github.com/flox/flox/pull/1822 because it's unlikely to merge conflict now that the structure is in place
- I haven't yet thought about whether the breakdown of unit vs integration testing

**Comment by zmitchell** [comment]
> it will get the activation PID passed to it as a CLI arg

It _can_ get the activation PID passed to it as a CLI arg, but in normal operation it's going to infer it (it's going to fetch its parent's PID) since that's the only PID that's supported on Linux.
