### ISSUE TITLE
Flox overwrites ZSH HISTFILE setting

### ISSUE THREAD

**Issue by eikenb** [flox/flox#1851]
**Describe the bug:**

In the activate.d/zsh script HISTFILE gets set to "$HOME/.zsh_history" overwriting the setting of the parent shell.

**Steps to reproduce:**
1. activate flox
2. shell is using wrong HISTFILE

Result:
New history and history completions use wrong HISTFILE

Expected:
History to use my $HISTFILE setting

**flox Version (run `flox --version` if possible):**
1.2.2

**`uname -a` output:**
Linux alia 6.9.7+bpo-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.9.7-1~bpo12+1 (2024-07-03) x86_64 GNU/Linux

**Comment by mkenigs** [comment]
I think to fix this all we need to do is `export HISTFILE="${HISTFILE:-$HOME/.zsh_history}". But `/etc/zshrc` on macOS has `HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history`, which we don't want being respected, since ZDOTDIR is read-only and in the nix store for us. I believe we should be avoiding that since we're setting `NO_GLOBAL_RCS`, but we should double check

**Comment by dcarley** [comment]
@eikenb we've merged the fix for this in https://github.com/flox/flox/issues/2039 and it will be available in the next release (after v1.3.1). Thanks for reporting it and please feel free to re-open the issue if you're still running into problems.
