### ISSUE TITLE
Sometimes services fail to start

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1892]
We've seen the failure `❌ Failed to start services, see /tmp/tmp.oq0I0JXHwI for logs` in a few places

@rossturk has run into it locally
https://flox-dev.slack.com/archives/C06T9RL3BQT/p1722529750786059

`process-compose can run generated config file` has flaked in CI
https://github.com/flox/flox/actions/runs/10147755318/job/28059441454?pr=1849#step:6:384

`can start redis-server and access it using redis-cli` and `stop: errors without stopping any services if preceeding service doesn't exist in` have flaked in the same CI run
https://github.com/flox/flox/actions/runs/10252571018/job/28364165605#step:6:392

**Comment by dcarley** [comment]
This is a bit of a grab bag of issues that might prove to be unrelated or since fixed.

One concrete thing that did come up though is that we should use a qualified path for `sleep` in `flox_never_exit` so that we're not depending on binaries from the host OS which might not support the `infinity` argument. There are some other ideas of non-polling replacements [here](https://stackoverflow.com/questions/2935183/bash-infinite-sleep-infinite-blocking) but I don't think any of them are particularly easier to plumb in.

**Comment by mkenigs** [comment]
We can close this after using a Nix-provided `sleep`

**Comment by ysndr** [comment]
Do we have specific tests we need to add for this?
I believe its hard to test these "negative" cases again.

**Comment by mkenigs** [comment]
Saw this again in https://github.com/flox/flox/actions/runs/10390132193/job/28770507812?pr=1920#step:6:410
