### ISSUE TITLE
start services for remote activations

### ISSUE THREAD

**Issue by ysndr** [flox/flox#1921]
### Motivation

**When** I have an interesting ephermeral remote environment that contains services
**I need** an activation with services starting
**So I can** have the environment without having to `flox pull` it first

### Acceptance Criteria

`flox activate -r ghudgins/postgres-example --start-services` works

### Original issue

**Title: Remove `--remote` option for service commands**

Currently service commands use the `EnvironmentSelect` parser and require validation of the provided environment, failing later than necessary if a remote environment was provided.

At least for argument parsing matters we should provide a parser for `--dir <path> -> Option<PathBuf>` only.
We might still want to map that to an `EnvironmentSelect` variant in order maintain the ability to get the "current environment" (which can still be a remote env in which case we continue to err)

We may revisit this once we have a plan to run services for remote environments

**Comment by ghudgins** [comment]
can we instead refactor this into "allow starting services for remote environments" and just make it so that there is a single instance of a remote environment on a given machine?

i've already found myself wanting to `flox activate -r something/something -s` without having to `flox pull` first and I imagine the marketing team isn't far behind wanting this

**Comment by mkenigs** [comment]
That's technically not difficult - so technically the answer is yes

We punted because design isn't obvious. If we make it such that there's a single instance of a remote env on a given machine, then `flox activate -r something/something -s` followed by someone else pushing changes to the services in `something/something` and `flox activate -r something/something -s` in a completely separate shell will warn that old services are still running

I think activation is getting a bit confusing - I'm starting to wonder if we have some design debt:
- `profile` runs once per activation of any kind
- hooks run once per distinct shell (i.e. not a subshell)
- services run once per environment on disk
- `FLOX_ENV_CACHE` gets cleaned up after any `-r something/something` invocation
- If we make this change, remote services won't be cleaned up after any `-r something/something` invocation

**Comment by ghudgins** [comment]
agree, I think coupled to the remote services invocation is the updating of how remote activations work to treat it as 1:1 on the machine (instead of each activation being its own instance). this to me seems like the right emergent design based on how we defined the mental model for environment activation in the service management design. so yeah, to add remote activation -s we should also make each `activate -r` use a single shared instance that can be connected to...

**Comment by ghudgins** [comment]
my point is I don't really want to do this issue, i'd rather do those issues instead

**Comment by ghudgins** [comment]
also, this doc should help guide us around splitting this into those issues https://docs.google.com/document/d/1j-fHIxQMCjwHRgyD_ETRfGEMndeel8yKpPE8wFnQ4DU/edit

**Comment by mkenigs** [comment]
@zmitchell did you mean to self-assign this?

**Comment by zmitchell** [comment]
I had just barely started working on it on Friday, but I won't have time to work on it between writing and computer issues. @dcarley had mentioned it being an item for the European backlog tomorrow morning.

**Comment by mkenigs** [comment]
👍 moved
