### ISSUE TITLE
Add `[build]` section to manifest

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1943]
Add a build section with the following format to the manifest

```
build.<name> = {
  command    = <STRING>
, files      = null | [ “path1”, “path2”, … ] /* optional, build can write to $out */
, systems    = null | [ <STRING>, … ]
}
```

**Comment by mkenigs** [comment]
I think we should probably just go ahead and add `build.<name>.sandbox = (null|”off”|”pure”)` but I don't feel too strongly

**Comment by ysndr** [comment]
Part of this is already implemented in https://github.com/flox/flox/pull/1802.

`build.<name>.command  = <STRING>`

Is already supported on that branch.
In addition, `buildenv` was extended to render the command as file into the environment.

If we were to start form there, what is left is:

- [ ] rebase #1802 onto main (we have since touched the manifest service descriptor to add `is_daemon` and `shutdown`, those changes likely conflict in the diff but should be easy to resolve.
- [ ] add `files` and `systems` attributes -- we dont need to do anything with these yet.
- [ ] add pkgdb unit test for buildenv to assert that build commands are being written to the resulting env

> I think we should probably just go ahead and add `build.<name>.sandbox = (null|”off”|”pure”)` but I don't feel too strongly

Considering adding fields especially, reasonably optional ones is simple compared to removing them I'd lean towards keeping that field out for now until we add and evaluate more modes

**Comment by limeytexan** [comment]
> I think we should probably just go ahead and add `build.<name>.sandbox = (null|”off”|”pure”)` but I don't feel too strongly

Discussed with Graham - given that we expect users to almost immediately hit that brick wall of requiring network access, and that this is literally the only "CLI Scaffolding" work to be done for the second phase of the manifest builds project, we can go ahead and include the parsing of this attribute up front in this issue. Please do include it in this first pass - @mkenigs would you like me to update the issue description above?

Also by way of background, product will continue to present the "pure" mode first and independently of the "off" mode by virtue of not including the sandbox attribute in the manifest. In that regard we will configure the manifest builds to treat `sandbox == null` the same as `sandbox == "pure"`. Please shout if anyone doesn't agree with that!

**Comment by mkenigs** [comment]
> Discussed with Graham - given that we expect users to almost immediately hit that brick wall of requiring network access, and that this is literally the only "CLI Scaffolding" work to be done for the second phase of the manifest builds project, we can go ahead and include the parsing of this attribute up front in this issue. Please do include it in this first pass - @mkenigs would you like me to update the issue description above?

Sure - I think this is trivial enough that it really doesn't matter too much either way

**Comment by ysndr** [comment]
Added the sandbox setting as well
