### ISSUE TITLE
Update `buildenv` to write build command to built environment

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1944]
For every `build.<build-id>.command` in the manifest portion of the lockfile, `pkgdb buildenv` should 
- create an `executable` file at `<env store-path>/package-builds.d/<build-id>`
- write the content of the command to that file.
- ignore other attributes in `build.<build-id>` unless we add additional attributes that influence the contents of the file.

**Comment by mkenigs** [comment]
Seems okay to me

**Comment by limeytexan** [comment]
> create an **executable file** ...

Strictly speaking this isn't necessary because the builder will specify the specific bash interpreter that ships with flox, so my inclination would be to _not_ make it executable, and maybe even to give it a ".bash" suffix to underscore that it will only ever be evaluated using bash. I also recall that this requirement came about because of the bugs with `activate` that are due to be addressed with #1823. So ... my inclination would be to drop the executable bit, although it being set doesn't actually change anything.
