### ISSUE TITLE
Changes to activation scripts with new Flox release and existing environment

### ISSUE THREAD

**Issue by dcarley** [flox/flox#1974]
**Describe the bug:**
Features and bug fixes that are applied to the activation scripts in newer Flox versions aren't automatically applied to existing environments if they are already built.

This has caused frequent confusion and misidentified bugs while we have been testing service management internally because we've been making various changes to https://github.com/flox/flox/blob/main/assets/activation-scripts/activate. The current workaround is to make a whitespace change with `flox edit` to trigger a rebuild.

This won't be a problem with the initial release of service management in v1.3.0 because users will need to edit their manifests to add `[services]` which will trigger a rebuild with the latest activation scripts. It could cause us problems when releasing subsequent service management changes. CUDA is another good example, shown below.

**Steps to reproduce:**
1. Init, activate, and thus build a new environment with Flox v1.2.3
2. Upgrade to Flox v1.3.0 which has fixes for CUDA detection
3. Activate the environment again

**Result**: CUDA fixes aren't applied.
**Expected**: CUDA fixes are applied.

**Refinement notes:**
Use agreed implementation from https://www.notion.so/floxdev/003-Updating-activation-scripts-127744c8e3168062a07bce46e3b9d59e?pvs=4

**Comment by limeytexan** [comment]
Thanks @dcarley for logging this. As you note the `activate` script sits at the core of this issue, and there is really only one possible solution to this issue: use the new one for old environments.

Fortunately this ought to be fairly straightforward. At any point we have two versions of the `activate` script and associated `etc-profile` logic to choose from:
1. the one "baked into" the rendered `$FLOX_ENV`
2. the one that ships with the version of `flox` being invoked

As long as we design the `activate` and associated `etc-profile` scripts to properly key all its actions from `$FLOX_ENV` then we can choose which of these two to use at activation time, and expose that choice by way of configuration setting with env variable and CLI option flags.

Is this reproducible in the sense that `flox activate` today will deliver the exact same experience as `flox activate` tomorrow? Well, no .. but that's entirely the case - our goal in this instance is for the experience of running `flox activate` to evolve over time, just as the Tesla you drive this morning will likely provide a better driving experience than the very same Tesla you purchased a year ago. But if you really do want to simulate that _exact_ same experience of running `flox activate` as it was when the environment was rendered then _you can_, and you can choose which of those two behaviours you prefer to use by default.

Does that make sense? I know we talked/wrote about this previously/somewhere, but can't seem to find it, so happy to restart the conversation here. I happen to be deep in this script at the moment by way of #1823 and #1343 so would be happy to experiment a bit with this .. the last time I did we were actually pretty close.

**Comment by dcarley** [comment]
SGTM!

I'm not even sure that we have to support both forms. The current behaviour is only transiently consistent anyway, if you have built that environment on that host before and it's not been GC'ed. It's not like the lock provides any guarantees. Plus you could always downgrade to another Flox version if you needed to temporarily restore some behaviour.

Would using the activation scripts from the Flox release require rebuilding the environment? Do the activation scripts need to be linked into the environment in order to ensure any GC relationships?

**Comment by ysndr** [comment]
> Would using the activation scripts from the Flox release require rebuilding the environment? Do the activation scripts need to be linked into the environment in order to ensure any GC relationships?

Currently we ship activation scripts together with the environment for "standalonability" and to avoid the backward guarantees. I.e. an environment is internally consistent, but may be tied more loosely to specific versions of flox due to variable setup etc.
In that sense we have reduced our backwards compatible api to the call of activate.
Now I believe recently we have introduced _more_ knobs elsewhere, e.g. the cuda support is turned on/off in a `profile.d` script via `_FLOX_ENV_CUDA_SUPPORT`[1] which is set by flox [2].

IMO providing a stable/extensible interface to the `activate` script in an internally consistent environment is more maintainable than keeping different activate scripts compatible with the rest of scripts in an environment.

What we can address would be building new environments with new flox releases or "activation api schema version". Either of which written to the environment and used as a conditional for the rebuild skip.


[1] https://github.com/flox/flox/blob/099aefcc4694431b5de8ae7c0a50e86c453a6ae4/assets/activation-scripts/etc/profile.d/0800_cuda.sh#L22-L26 

[2] https://github.com/flox/flox/blob/099aefcc4694431b5de8ae7c0a50e86c453a6ae4/cli/flox/src/commands/activate.rs#L298-L305

**Comment by limeytexan** [comment]
> Would using the activation scripts from the Flox release require rebuilding the environment? 

No, it would not. The idea would be to make all scripts self-referencing and only pull the packages and various activation hooks, build scripts, etc from $FLOX_ENV as found in a different directory. (Currently they expect to be in the same place.)

> Do the activation scripts need to be linked into the environment in order to ensure any GC relationships?

A copy of the activation scripts are already included in the environment. It's essential that we provide this not only to be able to reproduce the activation experience as it existed when originally rendered, but also for use within containers (where flox will not be present).

> IMO providing a stable/extensible interface to the activate script in an internally consistent environment is more maintainable than keeping different activate scripts compatible with the rest of scripts in an environment.

I agree with this, which is yet another reason why we must include a copy of the activation scripts at the time of rendering within the environment itself, and I agree that this can cause instabilities with backwards-incompatible changes, but **I don't believe this a reason not to proceed with the plan** because the value is clearly there and we have many tools at our disposal to deal with incompatible environments/activation script combinations:

* configuration settings, env variables and CLI flags as noted above
* we can use versions to identify incompatible combinations
    * and in the event that the current flox CLI is incompatible with the rendered `$FLOX_ENV`, use the scripts from `$FLOX_ENV`
    * we can overload existing manifest schema version or come up with a new versioning mechanism

**Comment by dcarley** [comment]
Refinement notes:

- Versioning
  - I don't think that we need to build versioning in from day 1
  - We can add it later when we encounter our first breaking change.
  - Assuming that we aren't considering the current activation changes as "breaking" when released.
- Switching
  - Conditional in `activate.rs` and pass env var down to `activate`
  - Replace use of `@out@` and `$FLOX_ENV` with new env var in `activate` and child scripts.
  - How to reference bundled `flox-activation` scripts?
  - Expose an escape hatch to fallback to `$FLOX_ENV` with an env var for now.
- Cleanup
  - Is `activation_path` still the right name for the complete rendered environment when the activation scripts may be elsewhere?
  - Continue deprecating old-style `activate/` rather than `activate.d/` directories

**Comment by mkenigs** [comment]
>     * Re-calling `CoreEnvironment.build()` should always use the latest bundled scripts?

We would need to change `PathEnvironment::needs_rebuild` to detect a change as well
