### ISSUE TITLE
Define calling conventions for flox-build.mk

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#1998]
Related to https://github.com/flox/flox/issues/1978

- [x] define make targets
  - positional argumemts of `flox build` i.e list of packages (or empty to build all)
- [x] define configuration flags
  - `-C <.flox parent>`
  - `FLOX_ENV=<storePath or link to storePath>`
  - `-f $out/libexec/flox-build.mk`
- [x] define configuration flag passing (makeflags, env vars, json, json)
  - builder reads from `$FLOX_ENV/manifest.lock`
- [x] define env 
  - run with original environment
- [x] define outputs (what goes to stdout)
  - no explicit output, std{out,err} are inherited
  - expect `<target>-result` links to be created in `<.flox parent>`

I think this is better discussed between cli eng + @limeytexan  to avoid miscommunication

**Comment by limeytexan** [comment]
From a "black box" perspective the job of the CLI is to:

* invoke command, wait for it to finish
* capture stdout/stderr, relaying it in real time depending on flags
* if return code is zero, confirm existence of expected result-* symlink(s) and exit 0 if they're all there
* else display some number of lines of the captured stdout/stderr if it wasn't already displayed and exit with the same return code

So with that in mind here's a first stab at answers to the above:

- make targets:
    - the names of the packages to be built
    - or "all" for all known packages
    - or if no target is specified then "all"
- listing packages: the CLI is aware of all known packages listed in the manifest, so that's not the job of the makefile
- define configuration flags
    - not sure what you mean by that; the makefile requires access to the manifest build metadata (e.g. "sandbox"), so it needs a path from the CLI by which to read that
- define configuration flag passing (makeflags, env vars, json, json)
    - we will definitely need a way for users to pass arbitrary flags to the gnumake invocation (e.g. for `--print-data-base`) because we will not want to expose that same set of args for `flox build`
    - any variables should be passed by way of command line overrides rather than the environment (that would potentially pollute the build)
    - the required variables I'm aware of at this point are are:
        - `$FLOX_ENV` for kicking off the build script
        - runtime env for wrapping contents of `bin` (which we won't have at first; we'll instead use `$FLOX_ENV` for both)
- define env
    - call with clean env?
        - `flox build` should be able to work from _any env_, from a completely bare `env -i` environment to an activation of the build environment
    - nix config
        - `flox build` should not require _any_ extra Nix configuration not included in the default Flox installation; this includes the specification of any/all experimental features
    - git config
        - `flox build` needs only to perform `git ls-files`, which should be compatible with the user's own git settings, but we can harden this with a bespoke set of git configuration files as we have done in the past
- define outputs (what goes to stdout)
    - the flox manifest build output is easily tuned from within the Makefile, and we can use the same `flox -v` flags to increase the verbosity
    - output from the user-provided build script shall be included in its entirety
    - as mentioned above, we should have the ability to suppress output for successful builds, but it should also be easy to change this by way of a `flox config` setting to output all build logs by default
