### ISSUE TITLE
buildenv: build a filtered "runtime" environment

### ISSUE THREAD

**Issue by ysndr** [flox/flox#2064]
**Describe the feature:**

Particularly for manifest builds, we would like to produce environments that only include a specific group, i.e. are guaranteed to depend on a single catalog page / revision of nixpkgs.

**Describe a use case of this feature:**

After completing a manifest defined build, the build result will need to reference the pacakges it depends on at runtime. By default we may use the entire environment as that is what is available at build time.
Often this includes development tooling like compilers, etc that are _not_ required at runtime and would inflate the closure size of the package unnecessarily.

Control of this feature will be added to the manifest/build implementation through #2065

**Acceptance criteria:**
1. add an optional `--filter-group` flag to `buildenv`
2. if provided filter packages by their group. this should happen around the current filtering by system: https://github.com/flox/flox/blob/e8874c55b8bf871f2aabb4182893794e8cac9a08/pkgdb/src/buildenv/realise.cc#L852-L873
3. pkgdb test to verify filtering is successful

**Comment by limeytexan** [comment]
As discussed offline:

- we are thinking to create these manifest build "runtime" environments as additional outputs of the existing flox environment build because they are a) created at the same time and b) created from the same invocation/derivation
    - while we don't exactly know how we will make use of them, we expect there will be advantages to considering these packages as outputs of a single flox environment build as opposed to treating them as entirely independent builds
        - for example Nix will be aware that the outputs share a single build log and derivation, so `nix log <path_to_env>` will surface the build logs for all of the package outputs in a single stream
- we need to be able to build a different runtime environment output for each build specified in the manifest
    - if not explicitly specified in the manifest, the default runtime output should be a deep recursive linking of the `toplevel` package group
    - we should build an environment for each `build` found in the manifest, and if those happen to render the same exact package for multiple builds then that will be v. quick!

... and while we are in the neighbourhood, I would be sorely tempted to add support for the flox env "runtime" output as well, which is just like the normal flox env but with the profile built using the Nix `builtins.buildenv()` instead of performing the deep recursive linking.

**Comment by ysndr** [comment]
> as additional outputs of the existing flox environment build
> [..]
> need to be able to build a different runtime environment output for each build specified in the manifest

I strongly believe that introducing "`flox build` semantics` into the buildenv implementation, and conversely adding knowledge of `buildenv` outputs to the build subsystem goes against the idea of largely independent "blackboxy" subsystems.
In particular on the C++ side it adds (duplicate) logic to parse _manifests_ in even more detail. If those additional output are always built, we exercise C++ codepaths during every environment build, thus the risk of environment builds breaking because of issues with the `build` builds is much higher and neither is really tested in isolation.

Both `flox` and `flox-build.mk` need to be aware of the outputs at some point somewhat unnecessarily sharing knowledge.

The benefit is that it requires only a single buildenv call as opposed to potentially more for N many packages, which would be a speed optimization depending on the static overhead.

> for example Nix will be aware that the outputs share a single build log and derivation, so nix log <path_to_env> will surface the build logs for all of the package outputs in a single stream

based on the current implementation, nix wont have any build log, since there isnt even a deriver for an environment. The store path is literally created _in place_ within buildenv.
`pkgdb buildenv` uses the same approach as `nix profile`, where both create basicaly content addressed store-paths:

```shell
$ nix path-info /nix/var/nix/profiles/per-user/yannik/profile --json | jq
[
  {
    "ca": "fixed:r:sha256:0yjy3qp0qs6db3ra4irv3zpwypm2296mg3pw8z4ld5hnkh6ndl9l",
    "narHash": "sha256-NNFmDZwWlkbJR/yOV00Sol7P7x87R6LyWM1oDC4eXno=",
    "narSize": 316376,
    "path": "/nix/store/2j1qwga3vx8svcv260jjfld0d16na029-profile",
    "references": [
      "/nix/store/566f5isbvw014h7knmzmxa5l6hshx43k-hello-2.12.1",
      "/nix/store/d9vyl0v7piq5pym4g3xw5fpkvk4a7mfb-home-manager-path",
      "/nix/store/p7lchnxm76q901pzi27sd5rs4xfpnva8-flox-1.2.3-g1db89b0"
    ],
    "registrationTime": 1725545557,
    "valid": true
  }
]

$ nix path-info ./.flox/run/aarch64-darwin.vue --json | jq
[
  {
    "ca": "fixed:r:sha256:04ybgdvfz8yil08q06r83n7jis5k7pnz1911cq1iz7zd0152658x",
    "narHash": "sha256-HRUjSgDtnx8DZiGk8O09s+gojx0oG4ARoNGj73Z7yxM=",
    "narSize": 50560,
    "path": "/nix/store/ml3xn8rv3y2vc5q9lx1y1yi4603cnixc-environment",
    "references": [
      "/nix/store/1hyxmm8yk9g9jfnhgjq7lrv0vxpny7w4-package-build-scripts",
      "/nix/store/9sivnhfv6pdgdf02cw6hrbpb6ib83h9v-rsync-3.3.0",
      "/nix/store/clzfgrh8fmzgr8jmv2266b30qh4mqlxa-nodejs-20.16.0-libv8",
      "/nix/store/iikbj8fwd3msxvh747v22b0gpf1rckww-nodejs-20.16.0",
      "/nix/store/l0d3vf1cb4w2js21g8ra9wwg878cinv0-activation-scripts",
      "/nix/store/n56qxwrif4iljbpg5773qpdnzb7sahh3-lockfile",
      "/nix/store/nx3cpwpwyjb34m5ib6zq36qshw95bwrh-flox-activation-scripts",
      "/nix/store/qb5ydv2a3dzwwsiq1zjncb1s763zdi2h-nss-cacert-3.101",
      "/nix/store/spyn2n8l9ca1pkqn20l40l424xmqwda4-bash-5.2p26"
    ],
    "registrationTime": 1725629265,
    "valid": true
  }
]

# a "nix built" store path:

$ nix path-info /nix/store/mi48qq2yrscbx9k1kbsp6i8g0jyvpj7m-app-0.0.0 --json | jq
[
  {
    "deriver": "/nix/store/hbyrp92nhj2n8v53f9wmsgc2xx8vj2kc-app-0.0.0.drv",
    "narHash": "sha256-v4OIEW87scfWJMuBhI3N/PjN7nC4ZlLObmZ2K0BcelM=",
    "narSize": 79384,
    "path": "/nix/store/mi48qq2yrscbx9k1kbsp6i8g0jyvpj7m-app-0.0.0",
    "references": [],
    "registrationTime": 1725629240,
    "ultimate": true,
    "valid": true
  }
]
```

In addition the only build logs to be recovered are logs of incidental builds, although they _can_ be useful..

Supporting through a proper deriver would mean re-implementing builenv through nix(lang) and using `builtins.derivation` which seems to be quite an extension of the scope of the original issue, that is: "provide runtime envs for built packages".


As for a "runtime" variant of the environment, using `builtins.buildenv` is equivalent to running the current implementation (which is a fork of the implementation of `builtins.buildenv`) with  a toggle for deep overriding. I'd argue that maintaining a single builder with a flag will be more consistent than depending on two entirely different implementations for the same task.


I believe the core of the "issue" is that we have opted to implement env building using nix' approach for `nix profile` rather than a nix(-lang) implementation based on `nixpkgs.buildenv`.
reimplementing the `buildenv` command in nix(-lang) is of course always an option, although i'm not convinced its a requirement.

CC @flox/cli for awareness

**Comment by limeytexan** [comment]
> Acceptance criteria:
> 
> 1. add an optional --filter-group flag to buildenv

As I mentioned in [2065](https://github.com/flox/flox/issues/2065#issuecomment-2334408698) this needs to be an arbitrary filtering of _packages_, not groups.

Additionally, whether it be from a single derivation or not, we do need to proactively build all outputs every time we perform a flox environment build so that those storepaths can be subsequently available not only for builds but also for falling back to "runtime" mode with layered activations not involving the flox CLI (i.e. as performed by way of the activate script). And it should be straightforward to do exactly that, and link them from the `.flox` directory as we currently do for the one developer environment closure. So with that in mind I'm not sure whether you want to call `buildenv` once and have it create all the various outputs or call it multiple times with a `--filter-packages` option, but I wouldn't call the addition of this flag an acceptance criteria as much as it is a detail of your proposed implementation.

**Comment by limeytexan** [comment]
Thinking about this further, I'd think the best outcome at least for now would be to attach the additional closures to the [1] flox environment in the same way that it currently does, which is by way of the `run` symlink created in the `.flox` directory. That choice of naming is now somewhat questionable as it is in fact the _developer_ environment (fully-recursively-linked) closure, but regardless it would seem most straightforward to continue using this as the primary means of mapping the additional closures to the `$FLOX_ENV` variable.

If we were starting from scratch, I'd imagine something like this would be the ideal geography:
```
.flox
├── builds
│   └── bar
│       └──aarch64-darwin.tmp.nOhinM9ME0 -> /nix/store/5jxbipy58gf2yiida1qmc27613pgvd0b-environment
│   └── foo
│       └──aarch64-darwin.tmp.nOhinM9ME0 -> /nix/store/5jxbipy58gf2yiida1qmc27613pgvd0b-environment
├── develop
│   └── aarch64-darwin.tmp.nOhinM9ME0 -> /nix/store/5jxbipy58gf2yiida1qmc27613pgvd0b-environment
└── runtime
    └── aarch64-darwin.tmp.nOhinM9ME0 -> /nix/store/5jxbipy58gf2yiida1qmc27613pgvd0b-environment
```

... and that we would embed `develop` and `runtime` into the `PATH` depending on the layer level, and use `builds/<pkgname>/<system>/activate` as the wrapper script for manifest builds. All of this could then be automatically inferred from a single `$FLOX_ENV/..` path.

Regardless, the idea here is be to build _all_ of these different "env" closures as we build any flox environment. Creating these additional links does not change the size of the closure because all outputs will contain the same or fewer packages than the current developer environment closure.

@ysndr - I'll reach out directly by slack to see if we can find time to chat briefly between meetings this week. Thanks for looking into this!

**Comment by limeytexan** [comment]
This was pretty much completed with #2226. The work to pass the individual build outputs to be used in the actual manifest builds will be done in a followup ticket.
