### ISSUE TITLE
Fix build_depending_on_another_build flakey test

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#2116]
`providers::build::tests::build_depending_on_another_build` has been flaking with:

```
error: cannot connect to socket at '/nix/var/nix/gc-socket/socket': No such file or directory
```

See https://github.com/flox/flox/actions/runs/10998438652/job/30536358666?pr=2115#step:7:1712

**Comment by ysndr** [comment]
looks like a nix issue https://github.com/NixOS/nix/issues/7370 which was fixed in https://github.com/NixOS/nix/commit/c5fdbdae321903740e0e735aa89fab5647992687#diff-07fc1ace31833e9e15b43ff87b2e44726feba7431c541de3662e77220bb8698fL144 but wasnt backported to 2.18 
https://github.com/NixOS/nix/blob/d4d300c2084b5e81ee0ea2aba8215d03133f14f8/src/libstore/gc.cc#L145-L151


we can try applying that particular patch to our nix 2.18 while 2.18 is the current nix in nixpkgs

**Comment by mkenigs** [comment]
Per https://github.com/flox/flox/pull/2126#discussion_r1773641293
> I think it's worth merging without any additional verification about whether it resolves our specific problem in https://github.com/flox/flox/issues/2116 and we can re-open if we find that it doesn't help.

**Comment by ysndr** [comment]
Apparently we still run into this on `main`: https://github.com/flox/flox/actions/runs/11033090237/job/30643465940#step:7:633

**Comment by ysndr** [comment]
attempt to close via https://github.com/flox/flox/pull/2141
