### ISSUE TITLE
Builds: Run patchelf on elf binaries even if sandbox is off

### ISSUE THREAD

**Issue by stahnma** [flox/flox#2117]
**Describe the bug:**

When doing a go project glibc linked against could be system vs nix provided. Let's patch it to ensure it's the nix binary.

**Steps to reproduce:**
1. Build a go project (I used vhs)
2. Run `strace -e openat ./.vhs-wrapped |& less`
3. See it linked agsinst system glibc

Result:

Expected:

Linked against the Flox provided libc

**Flox Version (run `flox --version` if possible):**

1.3.2-27-g04c258a5

**`uname -a` output:**

Linux giga2 6.10.6-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Aug 19 14:09:30 UTC 2024 x86_64 GNU/Linux

**Comment by mkenigs** [comment]
- To test: run a minimal build, check that the interpreter is coming from Nix

**Comment by mkenigs** [comment]
@limeytexan to pair with someone

**Comment by limeytexan** [comment]
I'm not able to reproduce when compiling GNU hello:

* `wget https://ftp.gnu.org/gnu/hello/hello-2.12.tar.gz`
* `tar xzfp hello-2.12.tar.gz`
* `git init .`
* `git add .`
* `git commit -am init`
* `flox init .`
* `flox install gcc gnumake help2man patchelf`
* `flox edit`, then create this stanza:
```
[build]
hello.command = '''
  ./configure --prefix=$out
  make
  make install
'''
```
* `flox build`
* `strace -e openat result-hello/bin/.hello-wrapped | grep glibc`

**Comment by limeytexan** [comment]
Ah .. alas I just noted the requirement that this be a `go` project.  :-\

So I tried https://github.com/golang/example but that compiles statically.

🤔

**Comment by stahnma** [comment]
@limeytexan `outyet` in that example project reproduces the issue.

**Comment by limeytexan** [comment]
> @limeytexan outyet in that example project reproduces the issue.

Still having problems .. "doesn't work on my machine".  :-\

```
flox [example] brantley@ubuntu:~/src/example/outyet$ go build
flox [example] brantley@ubuntu:~/src/example/outyet$ ldd outyet 
        not a dynamic executable
flox [example] brantley@ubuntu:~/src/example/outyet$ flox list
go: go (1.22.7)
flox [example] brantley@ubuntu:~/src/example/outyet$ 
```

And Dan when I try your example I get:
```
flox [example] brantley@ubuntu:~/src/example/foobar$ go build main.go
go: no Go source files
```

Googling tells me this is likely because I'm lacking `cgo` in my environment? So I removed `go` and installed `gccgo` and now it does a thing which creates a dynamic executable!

So our helpful `flox init` helper didn't help this time.  Hmmm ...

Anyway, back to the task at hand ... that test program seems to link correctly against the Nix libc:
```
flox [foobar] brantley@ubuntu:/tmp/foobar$ ldd ./foobar
        linux-vdso.so.1 (0x0000ffff934ae000)
        libgo.so.14 => /nix/store/gycvwwdvxdpzjkjkcf8b1w218bh0zn7r-gccgo-9.5.0/lib/libgo.so.14 (0x0000ffff91cc0000)
        libm.so.6 => /nix/store/hk72avjvcf83adwq16jz7y6kmx047w2h-glibc-2.35-224/lib/libm.so.6 (0x0000ffff91c10000)
        libgcc_s.so.1 => /nix/store/hk72avjvcf83adwq16jz7y6kmx047w2h-glibc-2.35-224/lib/libgcc_s.so.1 (0x0000ffff91be0000)
        libc.so.6 => /nix/store/hk72avjvcf83adwq16jz7y6kmx047w2h-glibc-2.35-224/lib/libc.so.6 (0x0000ffff91a30000)
        libpthread.so.0 => /nix/store/hk72avjvcf83adwq16jz7y6kmx047w2h-glibc-2.35-224/lib/libpthread.so.0 (0x0000ffff91a00000)
        /nix/store/hk72avjvcf83adwq16jz7y6kmx047w2h-glibc-2.35-224/lib/ld-linux-aarch64.so.1 (0x0000ffff93471000)
```

So I tried charmbracelet/vhs and couldn't get it to build with gccgo.

Then I tried compiling the golang/example and got it to compile with gccgo, but again it was [correctly] linking against the Nix version of libc.

So ... bottom line can't reproduce the problem, but I strongly suspect the fix is as mentioned [above](https://github.com/flox/flox/issues/2117#issuecomment-2385586875). @dcarley would love your help to confirm this if you can get a reproducer!

**Comment by limeytexan** [comment]
Thanks Dan - that explains a lot! I deliberately run my Ubuntu system with the bare minimal installation so that explains why I was seeing this behaviour and y'all weren't. 

Happy to leave this in your capable hands, but I may tinker in flight depending on the quality of the WiFi.
