### ISSUE TITLE
Wait for all PIDs in the watchdog

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#2129]
Currently the watchdog only monitors its own PID. Instead, it should wait until all PIDs in the registry have exited, and then it should trigger cleanup.

Eventually, we'll only ever start one watchdog, but as a temporary solution, this means when the watchdog starts, if another PID has already been added to the registry, that watchdog should do nothing and exit immediately.

**Comment by mkenigs** [comment]
Questions:
- The watchdog will need to poll the registry. When will it do that? Periodically? Only when it's deregistering a PID?
- Should the watchdog monitor the PIDs of all activations, or should it treat the list of activations more like a queue and only monitor one at a time?
- What are the details of when and how the watchdog needs to lock the registry? Are there any races we anticipate?

**Comment by mkenigs** [comment]
- Should the watchdog update the activations.json file every time it notices a PID exits? Or just maintain a list in memory?

**Comment by dcarley** [comment]
Continuing thread from https://docs.google.com/document/d/1XLpxgJx-x_yBFCQVyRy6QKDMa27UkrB27QssMXhqL7M/edit?disco=AAABTodqAs8

We'll need to make sure that `flox-watchdog` tracks new activation PIDs as they are added to `activations.json` by `flox-activation` otherwise we might trigger clean-up too early if `flox-watchdog` doesn't know about a new (and potentially last) activation in a timely manner. This might require additional locking and/or signalling between the two processes.

`flox-watchdog` probably doesn't need to care quite so much about old activation PIDs being removed from `activations.json` because it will notice the death of the PIDs anyway, so long as they're not monitored after their first death and hand-waving the likelihood of a PID being re-used between the polling intervals.

**Comment by mkenigs** [comment]
> We'll need to make sure that `flox-watchdog` tracks new activation PIDs as they are added to `activations.json` by `flox-activation` otherwise we might trigger clean-up too early if `flox-watchdog` doesn't know about a new (and potentially last) activation in a timely manner. This might require additional locking and/or signalling between the two processes.

The watchdog will need to lock `activations.json` before running cleanup, so I figure it can lock, check if there are any PIDs it doesn't know about yet, and if not, then it can run cleanup. To me that seems easier than signalling?
