### ISSUE TITLE
Start watchdog in activate (was: flox-activations)

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#2130]
Instead of launching the watchdog from the CLI, launch it from `flox-activations` during `start`

**Comment by mkenigs** [comment]
Args the watchdog needs:
- disable metrics: will be needed by so might as well add an env var
- PID: accessible in Bash (`$$`)
- Log dir: already passed to Bash via _FLOX_ENV_LOG_DIR
- _FLOX_WATCHDOG_LOG_LEVEL: currently hardcoded in Rust, we can just hardcode in Bash instead
- Socket: can be derived from path_hash. We'll probably want to change this slightly after the refactor to be the hash of `FLOX_ENV` rather than the hash of `.flox`. But I think the shape of what we do will be pretty much the same. We'll need to hash in `flox-activation`. So we may temporarily need to thread `.flox` through to the activation script but that will be a shortlived change
- Hash: same as above
- Registry: this will change after the refactor, so we can probably just hardcode this in Bash and/or the watchdog for now

We could defer this change until https://github.com/flox/flox/issues/2135, but but my thinking is
- We should make watchdog changes early
- The only additional work from doing this now is temporarily threading `.flox` through
- https://github.com/flox/flox/issues/2135 is already too big so it's okay to do a small amount of extra work to split something off
So we should probably go ahead and just do it first

**Comment by mkenigs** [comment]
Beware of merge conflicts with https://github.com/flox/flox/issues/2134

**Comment by dcarley** [comment]
Notes from meeting:

> Is this going to break containers which don't have `flox-watchdog` per [this thread](https://docs.google.com/document/d/1XLpxgJx-x_yBFCQVyRy6QKDMa27UkrB27QssMXhqL7M/edit?disco=AAABVt5L0bI)?

We'll make it conditional for now, either by passing a way to identify that it's a container or whether the binary is on the PATH. Will need work later on to make any of this work in containers.

> So I think it would be easier to unconditionally pass `_FLOX_SERVICES_SOCKET`:

We're leaning towards this because `activate` already needs it when starting services and we won't have `flox-activations` wired in yet. We can move it later once everything is wired in. It might make sense to put the socket within the activation dir if we can verify that we won't run into path length issues again (particularly for tests which root them within a temp dir).

**Comment by dcarley** [comment]
> launch it in the activation script after sourcing hook.on-activate

Can you describe why it needs to come after `hook.on-activate`? I don't think the `flox-watchdog` depends on anything from the user environment, unlike `process-compose`.

Could it alternatively be launched from `flox-activations` where we get some safety of writing code in Rust instead of shell?

**Comment by mkenigs** [comment]
> > launch it in the activation script after sourcing hook.on-activate
> 
> Can you describe why it needs to come after `hook.on-activate`? I don't think the `flox-watchdog` depends on anything from the user environment, unlike `process-compose`.
> 
> Could it alternatively be launched from `flox-activations` where we get some safety of writing code in Rust instead of shell?

Hmm that's a good point, we could probably start it in `start-or-attach` as soon as we recognize we need to start. That's also the earliest point at which it makes sense to do some cleanup (i.e. remove environment just added to activations.json from activations.json)

**Comment by mkenigs** [comment]
I think the idea was that ultimately we may start `process-compose` as part of `start` and then start the watchdog immediately after that. But for cleaning up activations.json it would probably be fine to start the watchdog sooner

**Comment by limeytexan** [comment]
> > Can you describe why it needs to come after hook.on-activate? I don't think the flox-watchdog depends on anything from the user environment, unlike process-compose.

> That's also the earliest point at which it makes sense to do some cleanup (i.e. remove environment just added to activations.json from activations.json)

As Matthew says, we want to start the watchdog as early as possible once there's something to clean up, but late enough that it has all the info it needs to do its job. If it doesn't need anything from process compose (e.g. an ephemeral socket path returned by the PC startup or whatever) then yeah I suppose it can start earlier.

> Could it alternatively be launched from flox-activations where we get some safety of writing code in Rust instead of shell?

I'd say we should definitely start it directly from `start-or-attach`. I'm not sure of what "safety" you speak but I do recall mention of launching the watchdog in the background with `&` - an alternative to that would be to launch it with [daemonize(1)](https://linux.die.net/man/1/daemonize) but it all depends what you're aiming to accomplish. Are you just wanting to see the watchdog running outside of the process tree so that it's always consistent? If so then a simple `eval <(daemonize watchdog)` invocation with the watchdog emitting something like `export FLOX_WATCHDOG_{PID,SOCKET,WHATEVER}=xxx` would do the trick. That would allow the activated environment to know precise information about its watchdog which I presume would be useful.

**Comment by dcarley** [comment]
We don't currently need anything back from the watchdog or `process-compose` because everything they need is known early on and passed down (e.g. the socket path for an environment is deterministic and the watchdog skips cleaning up `process-compose` if it doesn't exist at termination). If we have some need for the watchdog PID in the future then it would also be easier to store that from `flox-activations` in Rust rather than `activate` in shell.

Looks like we have consensus and Matthew has already flagged the dependency change [here](https://flox-dev.slack.com/archives/C05P6A5J6U8/p1727904369289919). I can update this ticket if one of you can update the [diagram](https://docs.google.com/document/d/1XLpxgJx-x_yBFCQVyRy6QKDMa27UkrB27QssMXhqL7M/edit#heading=h.yc3a42iutwil)?

> I'm not sure of what "safety" you speak 

I just want to avoid footguns from writing shell script where possible 😄 

> Are you just wanting to see the watchdog running outside of the process tree so that it's always consistent with the "in-place" activation mode where it is always re-parented by init because its parent always exits?

I didn't have this in mind. Just to make sure that we're on the same page though; I had assumed that the watchdog would initially be parented to the "start" activation for the convenience of it showing up in a process tree where possible but that we should expect it might eventually be re-parented to PID1 if there are subsequent "attach" activations and that first activation exits, now that there will only be one watchdog for all activations of an environment and that we don't depend on the parent/child relationship for `prctl`.

**Comment by mkenigs** [comment]
> I didn't have this in mind. Just to make sure that we're on the same page though; I had assumed that the watchdog would initially be parented to the "start" activation for the convenience of it showing up in a process tree where possible but that we should expect it might eventually be re-parented to PID1 if there are subsequent "attach" activations and that first activation exits, now that there will only be one watchdog for all activations of an environment and that we don't depend on the parent/child relationship for `prctl`.

If we fork `start-or-attach` which forks the `flox-watchdog` and then `start-or-attach` exits, won't `flox-watchdog` get reparented immediately? I think that's fine but want to make sure I'm understanding

**Comment by dcarley** [comment]
> If we fork `start-or-attach` which forks `flox-watchdog` and then `start-or-attach` exits, won't `flox-watchdog` get reparented immediately? I think that's fine but want to make sure I'm understanding

That's true. Bottom line is that the watchdog will get re-parented but we don't care either way.

**Comment by mkenigs** [comment]
Chatted with @limeytexan sync, the comment he left earlier was a typo

Summary
- We should launch the watchdog after running hook.on-activate, because we may want the watchdog to run deactivation scripts at some point which might need env vars from hook.on-activate
- We need to start the watchdog before setting `ready = true` in the registry in case starting it fails
- We could launch the watchdog from env-ready
    - Cons: it's surprising to launch the watchdog as a side effect of something that might seem like it's only modifying the registry. This also means that when debugging logs, they come from `flox-activations` rather than from `start` in Bash which is surprising
    - Pros: consolidating logic in Rust

- If we're going to launch the watchdog from env-ready, should we just make those a single binary? That's basically what the watchdog has been doing
    - Whatever verb we choose, we should clearly comment in the activate script that it's doing two things, e.g. `activations env-ready; : this also starts the watchdog` so that in set -x output it's obvious

From @limeytexan's perspective if we leave this as two binaries, it makes more sense to use daemonize in Bash. But his preference is one Rust binary. From mine it's worth doing it in Rust

@limeytexan will update the diagram however we decide

**Comment by dcarley** [comment]
Making a start on this and will rebase on https://github.com/flox/flox/pull/2256

**Comment by mkenigs** [comment]
Ended up starting the watchdog in Bash for reasons explained in https://github.com/flox/flox/pull/2276/commits/a916936f3adfea22eed3e4eff4ff6eae150a259b
