### ISSUE TITLE
Implement registry start-or-attach

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#2133]
`flox-activation start-or-attach --pid <PID1> --flox-env <path> --store-path <path>`

- Checks for activation of store_path with some active PID2
- To attach: adds `{pid, expiration = None}`
- To start: adds `{ id: new_uuid(), store_path, ready: false, [{ pid, expiration = None }] }`
- Loops for ? seconds if there’s an activation in activations.json that is not ready and the PID2 in attached_pids is still running
- Exits non-zero if attaching fails
- Prints `_FLOX_ATTACH=<true|false>`
- Prints `_FLOX_ACTIVATION_STATE_DIR=$XDG_RUNTIME_DIR/flox/hash(FLOX_ENV)/$id`
- Prints `_FLOX_ACTIVATION_ID=$id`

**Comment by mkenigs** [comment]
I think testing should be relatively straightforward for what this command does, but it might get more complicated once we need to test it in integration with the rest of the activation script

**Comment by dcarley** [comment]
> Loops for ? seconds if there’s an activation in activations.json that is not ready and the PID in attached_pids is still running

- How long is reasonable to wait before aborting? Could be hard to bound because it's dependent on how expensive an environment's hooks are.
- Do we need to go as far as checking that `attached_pids` is an activation and not some other process that has re-used the same PID?
- Should "attach" automatically fall back to "start" in the case where an activation isn't ready and the PIDs are no longer running?

> Prints `_FLOX_ACTIVATION_STATE_DIR=$XDG_RUNTIME_DIR/flox/hash(FLOX_ENV)/$id`

`hash()` comes from https://github.com/flox/flox/issues/2163

`FLOX_ENV` definition comes from: https://docs.google.com/document/d/1XLpxgJx-x_yBFCQVyRy6QKDMa27UkrB27QssMXhqL7M/edit#heading=h.ndq30f41d4qv

>> So we can define `FLOX_ENV` to be .flox/run/{system}.{name} for normal activations and the environment store path for container activations.
>>  
>> …
>> 
>> We’ll also use: $XDG_RUNTIME_DIR/flox/hash(FLOX_ENV)/$id
>> 
>> This contains bare.env, post-etc-profile.env, and post-hook.env files (which replace our current usage of _add_env and _del_env). bare.env is the environment before activation is run. post-etc-profile.env is the environment after running etc-profiles (this is added for future experimentation but is not currently used). post-hook.env is the environment after running etc-profiles and `hook.on-activate`

> `--flox-env <path> --store-path <path>`

`store-path` is only used for the lookup and `flox-env` is only used to construct `STATE_DIR`?
