### ISSUE TITLE
Drop v0 environment support in Rust

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#2202]
- Drop `TypedManifest::Pkgdb` and `TypedManifestPkgdb`
- Drop `LockedManifest::Pkgdb` and `LockedManifestPkgdb`

**Comment by mkenigs** [comment]
I think we should also drop `maybe_migrate_environment_to_v1` and `migrate_to_v1`. It was kinda painful to figure out all the places we modify environments and rebuild them, so I wish we could keep that knowledge without keeping dead code around. But what's really important is that we don't accidentally start locking again more than we actually have to. And I think we could probably achieve that by adding a test that makes sure we don't lock an already locked environment. We may even already have that

**Comment by zmitchell** [comment]
Also drop:
- `CoreEnvironmentError::ServicesWithV0`
- There's a bunch of associated tests for the migration routines we can drop as well
- There are some code paths in `pull` that deal with v0 manifests that can be simplified
- Anything returning `CoreEnvironmentError::LockingVersion0NotSupported` can be simplified/dropped
- A lot of the `ensure_locked`/`lockfile_if_*`/`lock*` routines on `CoreEnvironment` can be simplified

**Comment by zmitchell** [comment]
We also discussed getting rid of the TypedManifest/LockedManifest enums in favor of plain structs so that we don't need to match on single-variant enums. There's the risk that we have to add this back in after making a breaking change to the manifest or lockfile, but that is low-probability in the near future and the benefits to simplifying are worth it.
