### ISSUE TITLE
`publish` should allow "re-publishing"

### ISSUE THREAD

**Issue by ysndr** [flox/flox#222]
**Describe the feature:**

When binary cache information changes, it should be possible to simply "re-publish" the package.
At the moment uploading a snapshot at the same path is prohibited to ensure immutability (and allow performance optimizations, by skipping build and upload if a snapshot is already present).

**Acceptance criteria:**
1. if a snapshot already exists, flox will issue a warning 
2. [alternative a)] `flox publish` rewrites a file unconditionally
2. [alternative b)] `flox publish` aborts/requires `--allow-override` flag

**Comment by stahnma** [comment]
Shouldn't a publish be an exactly-once operation? If you publish a thing with one sha and then republish (and it was a rebuild, it will have a new sha) thus is not the same artifact. 

In my past life, I've just rejected a publish of anything that already exists. You need to change something about the package (name, version, release) -- something has to change otherwise there is no nonrepudiation for a package.

**Comment by ghudgins** [comment]
re-open the issue if you feel strongly the other way

**Comment by ysndr** [comment]
The issue came up with data as data unrelated to the artifact changed.
E.g. because your binary cache url changed, or package metadata changes (those don't affect the build output)
Currently, you'd need to either expressly delete the existing snapshots, or make a source change to force a new outPath/package hash
