### ISSUE TITLE
Fail an integration test if it leaves behind background processes

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#2258]
We've still been seeing some test runs timeout after 30 minutes, which most likely means a background process is leaving FD 3 open.

9/13/24 https://github.com/flox/flox/actions/runs/10852645599/job/30119220968
10/11/24 https://github.com/flox/flox/actions/runs/11296272539/job/31421015539
10/21/24 https://github.com/flox/flox/actions/runs/11436599296/job/31814660403

All 3 of those failures have happened on aarch64-linux.

We should fail a test if it leaves FD 3 open so we have a better idea of where to start debugging.

**Comment by mkenigs** [comment]
- These hangs have let us find watchdog bugs in the past so always closing FD 3 doesn't seem like the best solution
- Could we use lsof? How would we know which processes we care about since they won't be children?
  - If we can distinguish processes, we could kill them and then exit
- If we can't figure out something with lsof, we could set subreaper, but that would be Linux only

**Comment by mkenigs** [comment]
- Could we use rexpect to do this somehow?
- Could we use an env var to tell process-compose to save its PID somewhere?

**Comment by dcarley** [comment]
There are two slightly conflated issues, that we:

1. want to know when backgrounded processes (like `process-compose`) are left after the test suite finishes
  a. which we're currently relying on Bats FD3 blocking for
2. don't want the test suite to block forever
  b. which we're currently relying on CI timeouts for

FD3 has a useful side-effect of allowing us to identify processes in `lsof` by the Nix or Bats temp dir but obviously we lose this if we close the FDs. Besides, it seems that closing FD 3/4 isn't enough:

- https://github.com/bats-core/bats-core/issues/1021

What we should really be leaning on though is letting Bats timeout the tests rather than letting CI do it by brute force, but there appears to be a bug with how it kills child processes:

- https://github.com/bats-core/bats-core/issues/1020

I _suspect_ that solving this is probably easier in `rexpect` because we have slightly more control. We also only _really_ need for the service tests which background `process-compose`. I think that we should wait a couple of weeks before doing anything more on this particular issue so that we can get feedback from the Bats issues and have a better idea about how `rexpect` fits in.
