### ISSUE TITLE
Symlink extra buildenv outputs into ".flox" directory

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#2296]
With https://github.com/flox/flox/pull/2226 `buildenv` produces multiple closures, and activation in "runtime" mode amounts to setting `FLOX_ENV` to point to one of these outputs. Symlink the store paths produced by `buildenv` in the `.flox/run` directory.

The exact name of the symlink is to be determined.

**Comment by zmitchell** [comment]
I'm not caught up on exactly how #2226 works, so I hope I'm correct in assuming that these are all completely separate closures.

As for naming, I think we could simply add another `.<name>` on the end of the existing symlink format e.g. `aarch64-darwin.<env name>.runtime`.

**Comment by mkenigs** [comment]
When we build an environment, we'll symlink both run and develop because then `flox activate` may not have to do any work/whoever is running `flox activate` may not have write permissions/we want to create the gcroot

We won't create build symlinks when running `flox activate`

**Comment by zmitchell** [comment]
We decided that the names for the symlinks will be implementor's choice, but we've expressed preference for
- The symlink suffix matching the name of the mode
- The modes are now called `run` and `dev`
- Creating a duplicate symlink to the existing one so that we can phase out the no-suffix symlink.

**Comment by ysndr** [comment]
* environment links for managed environments (and remote) currently do not have a `system` infix, any reason not to add that now?

* managed environments' links are currently stored in ~/.cache/flox/run, with the manifest being preserved in managed envs in the .flox, should we continue the assimilation and manage the links in .flox/run for managed envs as well?

* if you use existing activations with a new version of flox, now different paths will be updated (rather than what stored in e.g. FLOX_ENV), do we want to keep writing the old paths for a while for compatibility or are we ok with asking users to restart their flox shells? yes, according to the issue

> "Creating a duplicate symlink to the existing one so that we can phase out the no-suffix symlink." 

just confirming what this mean ( keep in place, or keep updating)
