### ISSUE TITLE
Fix flakey tests where services fail to start

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#2361]
Sometimes many tests fail with `Services failed to start`. Find and fix the underlying issue

https://github.com/flox/flox/actions/runs/11735543268/job/32693420488
https://github.com/flox/flox/actions/runs/11781146918/job/32813446255
https://github.com/flox/flox/actions/runs/11804832677/job/32886029939

Using https://github.com/flox/flox/pull/2332 could be helpful

**Comment by ysndr** [comment]
I've been measuring the startup time of these processes in CI in #2387.
To monitor startup times longer than the 1 second it flaked on, i bumped the startup timeout to 10 seconds.

* None of the several runs ive done over the last two days flaked on >10 seconds startup.
* An estimated 95% of runs, take below 100ms
* there are definitely occasional spikes, but none that look reproducible
* none took longer than a second yet as far as i can tell.

While i cant reproduce the tests flaking, its worth to consider that the machines we run these on are under less load currently, especially during CET mornings, and we also restarted and replaces some of the machines over the last few days.

> Using #2332 could be helpful

What do you expect to look for using strace, especially given  the low frequency we see this issue currently?

> And we should investigate when in its startup it's creating the socket

similarly what would that tell us?
we only see `process-compose list -u <socket>` fail.
which may be due to the socket not extisting or the daemon not responding or something in between.
What role would you attribute to when the socket is being created?

**Comment by mkenigs** [comment]
> What do you expect to look for using strace, especially given the low frequency we see this issue currently?
> 
> > And we should investigate when in its startup it's creating the socket
> 
> similarly what would that tell us? we only see `process-compose list -u <socket>` fail. which may be due to the socket not extisting or the daemon not responding or something in between. What role would you attribute to when the socket is being created?

I had forgotten we use `process-compose list` instead of just checking for the socket
