### ISSUE TITLE
Upload closure to specified cache when publishing

### ISSUE THREAD

**Issue by nicklewis** [flox/flox#2404]
`flox publish` should perform a `nix copy --to <store>` to the specified store before (or, if the logic is compelling, after) submitting the build to catalog-server. Rely on the user having preconfigured out of band any required auth to contact the store.

The paths need to be signed on the way out, so either accept a secret-key CLI parameter or expect it to be included in the cache URI.

Cache URI flag comes from https://github.com/flox/flox/issues/2403

**Comment by limeytexan** [comment]
Still agree that it's better to upload to cache first so that we can record the success of that cache upload as we publish the metadata to the catalog-server. If for some reason we crash before doing that then we'll have a package in the binary cache without a corresponding catalog "root" to protect it, and it will be cleaned up on a subsequent garbage collection run.
