### ISSUE TITLE
flox install/uninstall displays info about environment

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#361]
**When** I am installing with the imperative commands from an active shell
**I need** improved confirmation 
**So I can** be sure what just happened when layering multiple environments

# Acceptance criteria

_path env install_
**Given** I have `flox init --name showme` in `~/projectA`
**When** I `flox install curl`
**Then** I see a message `✅ 'curl' installed to environment showme at ~/projectA`

**And When** I `flox uninstall curl`
**Then** I see a message `🗑️  'curl' uninstalled from environment {name} at {path or remote}`

# Design
 `{✅ /🗑️ } {packagename} {installed/uninstalled} from environment {name} at {path or remote}`

**Comment by mkenigs** [comment]
@ghudgins for managed environments I did `environment owner/name at /some/path` so that it's fully disambiguous. We could just do `environment owner/name` or `environment owner/name at floxhub`, I'm not quite sure what you want - can you clarify or close if you're happy with `environment owner/name at /some/path`?

**Comment by ghudgins** [comment]
nice improvement over what I was asking. LGTM
