### ISSUE TITLE
flox search package@semver returns exact matches

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#370]
<img width="692" alt="image" src="https://github.com/flox/flox/assets/5465514/bad7db3e-7052-4321-b06f-35d55c458ec8">

I _don't_ expect `flox search curl@8.2.1` to return search results for `curlHTTP3`. I think it's because when you use a search engine you would need a wildcard in the middle of a string (`curl*@8.2.3`)

# Acceptance Criteria

_exact matches_
**Given** curl has version 8.2.1 (it does at the time of this writing)
**When** I `flox search curl@8.2.1`
**Then** I see exact match for only `curl` (no `curlHTTP3` or `curlMinimal`)

_nice to have: wildcards_
**Given** curl, curlHTTP3, curlMinimal has version 8.2.1 (it does at the time of this writing) 
**When** I `flox search curl*@8.2.1`
**Then** I see exact match for `curl`,`curlHTTP3`, and `curlMinimal`

cc @jennymahmoudi

**Comment by zmitchell** [comment]
This proposal feels like it overlaps a lot with `flox show` in the sense that `flox search` does a fuzzy search over a number of different fields, erring on the side of more results, whereas `flox show` specifically only shows you a single result.

With this particular search, you're actually still getting `curl` (the package you asked for), it just so happens that there are multiple `curl` packages with different features enabled, and because they're all actually the same piece of software it follows that they all have the same versions available. If you were getting `curl` and `foo-curl` where `foo-curl` has nothing to do with `curl` I would be more convinced that we need this particular feature.

**Comment by jennymahmoudi** [comment]
What is the use case for searching for a specific package with a specific version? Are you just checking that you have it correct? I'm trying to understand how other package managers handle this type of search but not finding any examples of how to include versions.

Based on my current understanding,`flox search` is for when you don't necessarily know the right package name or version (so fuzzy search is warranted); `flox show` is for when you know the exact package name and need more information, like available versions. 

We can create a semver search however we want, but currently this is behaving as I'd expect it to.
