### ISSUE TITLE
Refactor and clean up the EnvironmentError2 type

### ISSUE THREAD

**Issue by zmitchell** [flox/flox#375]
Currently all errors that could be encountered while doing _something_ with an environment are put into one big bucket called `EnvironmentError2`. The `2` comes from the fact that it was created while we still had another existing `EnvironmentError` type.

The current error type is approaching 100 lines long, which makes it hard to read and hard to determine whether an existing variant covers your use cases. Furthermore, there's guaranteed to be variants that are no longer used. To make matters worse, many of the existing error messages are simply the name of the enum variant. This is a bad user experience for any user that encounters one of these errors.

Tasks:
- Rename `EnvironmentError2` -> `EnvironmentError`
- Remove all unused variants
- Make variants  that fill broad categories e.g. `ManifestError`, `LockfileError`, `ActivateError`, `BuildError`, etc  (whatever makes sense)
- Create error types corresponding to the categories
- Move existing variants into the appropriate error types
- Give all variants descriptive error messages

**Comment by ghudgins** [comment]
@jennymahmoudi and I can help think through descriptive error messages for those cases

**Comment by zmitchell** [comment]
I just discovered this the other day, but for whoever ends up working on this ticket, almost all of the error variants that look like this:
```
enum SomeError {
    #[error("my error message about the inner error:  {0}")]
    TheErrorCase(InnerError)
}
```
should instead look like this:
```
enum SomeError {
    #[error("my error message about the inner error")]
    TheErrorCase(#[source] InnerError)
}
```
This will let the inner error be displayed as another layer in the backtrace as opposed to being printed on the same line as the `"my error..."` message. It looks much nicer.

**Comment by ghudgins** [comment]
LGTM. will do a comprehensive audit of error messages outside of the scope of this issue.

**Comment by ysndr** [comment]
@ghudgins I think this issue was mislabled as product and team-cli.

There are two seperate parts to this:
- internal refactoring of the error types we use around environments, ( i did some in the field I touched but not all ), **in order to**
- improve (non technical/internal) error messaging on the CLI. (different scope)
  - Optimally we can make great messaging on the cli layer without digging into the library
  - I think for now we try to keep the internally produced error messages as concise as possible

Anyway I think we should split out at least the latter part (certainly not a 2 estimate)

And possibly a separate product ticket to verify the messaging is correct

**Comment by ghudgins** [comment]
@ysndr can you split the one ticket out so we don't forget?
