### ISSUE TITLE
[pkgdb]: GitHub Action PR check to assert that changes to database schema are reflected in version number

### ISSUE THREAD

**Issue by aakropotkin** [flox/flox#514]
Create a simple GitHub Action which compares a PR's database schema against `main`.

If the schema has changed, assert that the schema version was also changed.

`sqlite3 <DBPATH> 'SELECT version FROM DbVersions WHERE name = "pkgdb_schema"';` will allow you to extract the version number.

`diff -q <( sqlite3 <DBPATH> '.schemas'; ) <( ...; )` ( possibly with `grep '^/* ';` ) could be a good starting point for detecting changed schemas.

**Comment by ghudgins** [comment]
is this still relevant?

**Comment by mkenigs** [comment]
I'd say we can close for now, and if we plan more schema changes we can re-open, but right now it doesn't seem worth doing

**Comment by oxcabe** [comment]
Hi! I've been working on this to since yesterday in order to familiarize myself with the project development, and just noticed it's closed now.

So far, my approach has been to create a [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) called `assert-schema-version`, whose functionality could be described as follows:

> Asserts that changes in database schema require upping the schema version number.
This action takes the path of a SQLite file as an input and annotates assertion failures as warnings.

It would just run `pkgdb scrape` against `github:flox/flox/main#flox-pkgdb`, generating a SQLite database file to diff the input database schema against.

There is also an optional flag, `strict`, which would [annotate](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-a-warning-message) assertion failures as errors instead of warnings. In this case, the action exits with an error code as well.

Also, if this isn't worth finishing, let me know. In that case, I'd still like to help with any issue that helps me become familiar with the codebase :slightly_smiling_face:.

**Comment by mkenigs** [comment]
Oh that's a bummer, sorry about that 😬 I think it would probably be more worthwhile working on something else, although I hate to throw away anything you've done already.

We have a few issues labeled with [good first issue](https://github.com/flox/flox/labels/good%20first%20issue). If you want to tackle one of those, just leave a comment saying you're working on it.

If none of those look interesting or you want to tackle something harder, you can ping me on our slack https://go.flox.dev/slack

**Comment by oxcabe** [comment]
No problem, this is pretty much on me since I didn't communicate my intentions properly :sweat_smile:
