### ISSUE TITLE
flox login timeout is too short

### ISSUE THREAD

**Issue by jennymahmoudi** [flox/flox#720]
**Describe the bug:**
When I log in to flox from the CLI (in this case, when I am prompted via flox push), the CLI times out after 30 seconds.

**Steps to reproduce:**
1. On the CLI, when unauthenticated, do `flox push`
2. Take more than 30 seconds to enter 8-digit code on the web

Result: 
* the auth0 web flow reports that the device is successfully connected
* the CLI reports an error:
`ERROR: Could not authorize via oauth: Could not authorize via oauth: Server returned error response`

Expected: 
Reasonable timeout length... 15 minutes?

**flox Version (run `flox --version` if possible): 0.3.6-192-g3ef8037**

**Comment by ghudgins** [comment]
+1 from participant today

**Comment by ysndr** [comment]
https://github.com/flox/flox/pull/737 uses timeouts from the `expires in` key from the auth provider.

* we should catch the error more specifically
* do we want to refresh the token for 15 minutes if the prev token expired -- suggest staying with the expires in time for now and turn that knob in auth0 if necessary

**Comment by jennymahmoudi** [comment]
> do we want to refresh the token for 15 minutes if the prev token expired -- suggest staying with the expires in time for now and turn that knob in auth0 if necessary

@ysndr is this a question for me?

**Comment by ysndr** [comment]
When we receive the verification token from the server (the 8-character code) we also get the metadata on how long that token is going to be valid.
To achieve "a reasonable timeout length" we can either, request a new token if the current one expires before our desired timeout, or, because we control the backend, increase the timeout server side.
I'd prefer we have that setting server side since the url might also change and just makes the flow kinda wonky if implemented in the cli.

@nicklewis will know if we can actually influence the timeout via auth0.

My questions two both of you @jennymahmoudi @nicklewis 

- are we in agree to change that server side if possible?
- how specific are those 15 minutes if we can't change the default server side
- how long is the default?

**Comment by jennymahmoudi** [comment]
> are we in agree to change that server side if possible?

yes

> how specific are those 15 minutes if we can't change the default server side

not specific. Right now it's almost guaranteed to fail bc it takes someone more than 30 seconds to complete the flow. I would say a comfortable minimum time would be 5 minutes. But ideally 15 minutes to allow for getting distracted.

> how long is the default?

I don't know

**Comment by ysndr** [comment]
the default timeout returned by the server is 900s i.e. 15minutes by pure coincidence :)

**Comment by ghudgins** [comment]
this LGTM. @jennymahmoudi if you see something missing feel free to reopen
