### ISSUE TITLE
Custom fetcher is used while building the manifest

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#768]
After #764, the lockfile will contain references to flakes of type `<scheme name>` (whatever is decided in #762). `pkgdb buildenv` needs to know how to build lockfiles containing those references. We may get this for free depending on how we add the fetcher, in which case this ticket can be closed when `pkgdb buildenv` is verified to work.

**Acceptance criteria:**
- `pkgdb buildenv` can handle flakes of type `<scheme name>` (whatever is decided in #762)
- `pkgdb buildenv` succeeds after pulling an environment to a different machine than where it was locked

**Comment by aakropotkin** [comment]
- It is not recommended to use these custom fetchers to implement _rules engine_ aliases or "hides"/removes because those are expected to change frequently and would result in a large number of vendored _wrapper versions_.
  + This may be useful for explicitly "adding" new subtrees such as `legacyPackages.<SYSTEM>.darwin` because those are expected to change infrequently and cannot be added to completed databases after the fact in a later layer of abstraction.
- Because this form currently only modifies `config` settings, it is only valuable in today's client during `buildenv` operations.
  + We can read "plain" `github` references from lockfiles, and swap them for `flox-nixpkgs` inputs by simply copying the `rev` field.
