### ISSUE TITLE
solution for auth configuration across tenants

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#786]
# Acceptance Criteria
* team selects a solution to have a separate auth system for dev and production and updates this ticket with AC (or creates a new ticket)

**Comment by ghudgins** [comment]
have a meeting with @nicklewis and the CLI team

**Comment by ysndr** [comment]
`flox auth {login,logout}` honor `_FLOX_OAUTH_{AUTH_URL,TOKEN_URL,DEVICE_AUTH_URL,CLIENT_ID}` (leading `_` as a marker for internal vars added in #788).

With those vars set it should be possible to use _any_ oauth provider (theoretically, dont try 🙃), certainly equivalently configured flox hub auth0 instances.

Since setting this up with 4 variables is quite a tedious, we could switch discovering them via oidconnect `well-known` behind an OAUTH_BASE_URL (might still need a configurable client id?).
We didn't do that for simplicity reasons, but if the need for _easy_ configuration of this exists now we can implement that rather quickly.

**Comment by nicklewis** [comment]
@ysndr This is great, thanks! We could actually implement an OIDC discovery endpoint in floxhub itself, so those endpoints can all be discovered that way. My original plan had been to proxy those routes to Auth0, but making them available via the API may be sufficient.

We will as far as I can tell still need a configurable client ID, which is a pain. We could possibly just compile in _two_ client IDs, a production ID that is used if floxhub == hub.flox.dev, and a dev ID that is used if it's anything else (assuming that all dev instances will use the single dev tenant).

I don't fully understand _why_ a client ID is necessary for the device workflow, so we might be able to avoid it eventually. That could be another thing we could make flox-api proxy on behalf of the CLI. That would allow any client to request a token through the device workflow by talking to flox-api, but any client could simply call `flox` to do the same today, so I don't think there's a security implication.
