### ISSUE TITLE
Dependabot PRs don't trigger push event

### ISSUE THREAD

**Issue by tomberek** [flox/flox#802]
This is likely due to the difference between actor and author?

Ref: https://github.com/flox/flox/actions/runs/7547095728/job/20546350948

**Comment by garbas** [comment]
If I remember correctly, this issue was created because some commits reported 28 total jobs and some only 14. With commit https://github.com/flox/flox/commit/9423c6f5d21a9aba247e5b849830288008a7335e we were assuming that this has something to do with the Dependabot. But it doesn't since all the following commits that were created by Dependabot are reporting 28 total jobs.

I think the reason is somewhere else, but generally each commit has 28 jobs for quite some time now and maybe the issue was on the GitHub's side.

@tomberek I think it is safe to close this issue.

**Comment by tomberek** [comment]
agreed... i think it is the jobs for the PR, and then the jobs for the merge queue.
