### ISSUE TITLE
flox doesn't re-activate correctly 

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#810]
STR:
be on a macOS machine

* have nvm on your system and a node version installed 
* `flox init`
* `flox activate`
* `flox install nodejs`
* `which node`

Expected: flox's node
Actual: nvm's node

+1 from user testing this week

**Comment by ghudgins** [comment]
note: re-activation does fix this issue. something is up with the reactivation logic

**Comment by ghudgins** [comment]
<img width="719" alt="image" src="https://github.com/flox/flox/assets/5465514/523dfef8-9421-42ee-8532-3cc284c850cb">

**Comment by mkenigs** [comment]
Does `hash -r` fix it?

**Comment by ghudgins** [comment]
yes

**Comment by ghudgins** [comment]
could flox run `hash -r` for me? could we fix this in scope of a bug or are we waiting for something bigger?

**Comment by mkenigs** [comment]
It would be easy to add for invocations like `eval $(flox activate)`. For `flox activate`, I think we'd have to do something a bit heavy handed like adding a pre-prompt hook, which would run a command between any commands the user was running, even if they had nothing to do with flox. We'd have to figure that out for each shell too, although we could probably just copy what direnv does. See e.g. https://tldp.org/HOWTO/Bash-Prompt-HOWTO/x264.html for Bash.

**Comment by ghudgins** [comment]
+1 from user research

**Comment by ghudgins** [comment]
+1 from user research

**Comment by ghudgins** [comment]
create a spike ticket for this sprint

**Comment by ghudgins** [comment]
these two also didn't work for a mac user

`flox install bats`

`flox install gcc`

**Comment by mkenigs** [comment]
Changing the estimate to 2, we should be able to solve this by adding something like this to our zsh activation:
```
real_flox="$(whence flox)"
source <(cat << EOF
flox() {
  "$real_flox" "\$@"
  export PATH="$PATH"
}
EOF
)
```

And something similar for bash

**Comment by billlevine** [comment]
TIL :
`set +h` for bash will disable hashing.
`setopt nohashcmds` and `setopt nohashdirs` works similarly for zsh

Adding those to the start of the activation script for the users shell should do the trick.

**Comment by mkenigs** [comment]
> TIL : `set +h` for bash will disable hashing. `setopt nohashcmds` and `setopt nohashdirs` works similarly for zsh
> 
> Adding those to the start of the activation script for the users shell should do the trick.

Strictly speaking that's more invasive as someone could have e.g. `hash -p path something` in an rc file, and then `flox activate` would fail. I kinda doubt anybody actually uses `hash`, but I don't know.

There's some other reasons it would be nice to be able to do things in a function:
- `flox exit` https://github.com/flox/flox/issues/959#issuecomment-1969942818
- Currently if a user `flox activate && flox edit # changes a var` we have to print https://github.com/flox/flox/blob/51371095972f0def7c313fdc6acd42bc0c1d75e6/cli/flox/src/commands/environment.rs#L166 We could smooth that over if we could throw things in a function

For just the hashing case, it does feel simpler to do `set +h`, but a part of me thinks it will be quite helpful to have somewhere we can hook into actually modifying the shell.

**Comment by billlevine** [comment]
A couple notes to play devil's advocate....
- If the user does a `hash -p ...`,  _anything_ we do to invalidate the hash table (like `export PATH...` or `hash -r`) will kill that as well. The only way to preserve something like that would be to selectively remove entries, or do some fancy footwork to re-create it.
- For `flox exit`, I just saw that as a message that the flox cli prints when someone issues `flox exit`.  I'm not sure how the function based approach helps with that.

- For the last scenario, I do see the value of updating the environment live without having to re-activate on certain changes like that.  IMO if we did that, we would want to hardcode the `flox` invocation to the one used at activation time.  I agree with this point.

A quick search found this: https://github.com/NixOS/nixpkgs/issues/69396
Looks like nix disables hashing in their shell... perhaps it's wise to follow suit?

**Comment by mkenigs** [comment]
>     If the user does a `hash -p ...`,  _anything_ we do to invalidate the hash table (like `export PATH...` or `hash -r`) will kill that as well. The only way to preserve something like that would be to selectively remove entries, or do some fancy footwork to re-create it.
Yeah I don't think we need to preserve what somebody has set with `hash`, I'm just trying to point out that this could create the situation that `bash -c "source somescript"` succeeds and `flox activate -- source somescript` could fail. Probably a very small edge case
> 
>     * For `flox exit`, I just saw that as a message that the flox cli prints when someone issues `flox exit`.  I'm not sure how the function based approach helps with that.
Meant to link a comment. Rather than just printing a message, we could actually just call `exit`

> A quick search found this: [NixOS/nixpkgs#69396](https://github.com/NixOS/nixpkgs/issues/69396) Looks like nix disables hashing in their shell... perhaps it's wise to follow suit?

I dunno that issue kinda goes to show that choosing to take the non-default path from every other OS has led to issues, even if they're resolvable

**Comment by billlevine** [comment]
Thinking carefully....  I think the `edit` and `exit` cases are useful, but also not a priority at the moment.  I also think, in general, if there is an explicit way to solve the issue, it's better to take that approach, rather than choosing one that resolves it via side-effect.  

In that issue mentioned, I feel the fact that the python code did not handle a situation where hashing is disabled is an issue in that code, and not a nix thing.   But, in the end it's the user that matters so I don't know that's a point to belabor.

I think I'm leaning towards the set +h approach now, and adding a ticket to revisit the function based approach for those other cases... and refer to the other three tickets (exit, edit, and this one).  And we can have a longer discussion at that point.

Consensus reached with @mkenigs 
Proceeding with `set +h` approach.
