### ISSUE TITLE
flox search printing less than 10 results

### ISSUE THREAD

**Issue by mkenigs** [flox/flox#813]
`flox search` only prints 7 results but says there are 10:
```
> flox search neovim
neovim               Vim text editor fork focused on extensibility and agility
libvterm-neovim      VT220/xterm/ECMA-48 terminal emulator library
neovim-gtk           Gtk ui for neovim
neovim-qt            Neovim client library and GUI, in Qt5
neovim-qt-unwrapped  Neovim client library and GUI, in Qt5
neovim-remote        A tool that helps controlling nvim processes from a terminal
neovim-unwrapped     Vim text editor fork focused on extensibility and agility

Showing 10 of 54 results. Use `flox search neovim --all` to see the full list.
Use `flox show <package>` to see available versions
```

# Acceptance Criteria

**Given** my environment has multiple systems defined in `[options.sytems]`
**When** I `flox search`
**Then** I get search results for the systems that match the environment's

**Comment by mkenigs** [comment]
Oh this happens when I have `systems = [ "aarch64-darwin", "x86_64-darwin" ]` in my manifest

**Comment by mkenigs** [comment]
We also need to fix install suggestions:
```
> flox install npm
ERROR: ❌  could not install npm
    Try 'flox install nodejs' instead.

    Here are a few other similar options:
      $ flox install nodejs
      $ flox install nodejs
      $ flox install nodejs
    ...or see up to 90 options with 'flox search nodejs'
```

**Comment by ysndr** [comment]
pkgdb will output individual search results for each _path_.
`flox search` is deduplicating the entries internally (taking not of the count _before_ causing the incorrect count being reported.
the suggestions only report back the output from pkgdb, here `legacyPackages.system_{1,2,3}.nodejs`.

I think past pkgdb it is too late to deduplicate
* less guarantees/information whether two packages with the same attrName are actually the same package,
* we basically have to request `|SYSTEMS| * n_results` search results since up to `(|SYSTEMS| - 1) / |SYSTEMS|` can be duplicates

Leaving the question: "what should be the result of `pkgdb search`?"
1. packages that match _all_ systems
2. packages that match _any_ system listed individually
3. packages that match _any_ system listed grouped `{"absPath": ["legacyPackages", null, "pkg"], systems: ["system1", "system2"], ...}`

My suggestion would be (3)

**Comment by mkenigs** [comment]
If we do 3 we'd have to change other parts of the schema as well because fields like `broken` might only apply to one system. I think we also need to think about adding `system` to the query we're passing. Suppose I have all four systems in my manifest, I `search` and find a package that only works on one system, and then I install it. Do we need to change search results? Do we need to display system in search results? Does install need to set only the working systems for that package in the manifest? Should we just error?

**Comment by ghudgins** [comment]
clarified AC for this. expect to see top 10 results from all systems declared in the environment's manifest

**Comment by mkenigs** [comment]
@ghudgins do you want to verify this one?

**Comment by ghudgins** [comment]
verified
