### ISSUE TITLE
Enable building flox, pkgdb, and nix with debug symbols on Linux

### ISSUE THREAD

**Issue by tomberek** [flox/flox#815]
For details see my three comments below - Zach

**Acceptance criteria:**
- Build `flox`, `pkgdb`, and `nix` with debug symbols on Linux.
- Leave a note in the `flake.nix` with instructions for how to enable builds with debug symbols

**Comment by zmitchell** [comment]
- We already build `flox` with debug symbols by default (this is the default for Rust)
- We can currently build `pkgdb` with the `just build-pkgdb-debug` command, but if you've already built `pkgdb` once you need to run a `just clean-pkgdb` so that `make` knows to rebuild.
- When we tried creating a debug build in the past we ran into issues trying to find the appropriate Nix interface to use.
    - It's unclear whether there's a single approach that can be applied uniformly to all packages, or if you need to enable specific debug variables for each package.
    - There's the `enableDebugging` function, but that appears to be broken on macOS: https://github.com/NixOS/nixpkgs/issues/207816

**Comment by zmitchell** [comment]
We decided to scope down this ticket:
- Just build `nix` with debug symbols instead of all transitive dependencies
- Only build debug symbols on Linux since `enableDebugging` doesn't work on macOS

**Comment by zmitchell** [comment]
You can already enable debug symbols for `flox` and `pkgdb` on all systems. Making a Justfile command that builds all three with debug symbols is trickier because you would need some way to switch between `nix` and a `nix-debug` package and make sure that the C++ code is compiled with the correct one.

It's a much easier process to simply comment out a line or uncomment out a line in the `flake.nix` file when you want debug symbols for `nix`.

**Comment by stahnma** [comment]
Can this be closed?

**Comment by mkenigs** [comment]
@zmitchell I don't see a comment in flake.nix, can you add that and then we can close?
