### ISSUE TITLE
Clean up and align ERROR headings and messages

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#849]
# Acceptance Criteria

* all errors emit `❌ ERROR: <<error text>>`
* find instances of this in code base, look for 🛑 and ❌
* Clean up error emoji from individual error texts if they're in use today
* don't bold error text
* don't indent the 2+ line of the error message automatically (still want to see indents on stack traces, but not designed error messages) - keep indenting if it's part of the message

**Comment by ghudgins** [comment]
@ysndr what do you think of our approach here? what would you estimate this at

**Comment by ysndr** [comment]
that depends a bit on the scope of this.

We basically planned to do this under the umbrella of separating _logging_ from _messaging_.

Currently we are doing so only by crate and logs from the library layer still creep under the nose of users (e.g. #838).

The plan is to use `tracing` provided logging handles for _logging_ (you might turn those on and change verbosity separately from _messaging_.
For _messaging_ we would either create our own functions or hook into `log` which we would use as a _messaging_ tool rather than _logging_.
Alternatively we do use the `tracing` stuff as a common bus but provide custom handles for messaging.

this would be an estimate of **5** plus **a few <= 3** tickets do deal with cleanup and adjusting.
I'm convinced we should do that eventually, but can defer to the push to better function tracing in general.

That brings me to the plan with **reduced scope**:

The formatting of our logging/messaging is pretty self contained.
We can leave the filtering as is for now and adjust the output format.

* don't print errors bold
* don't add (emoji) prefixes (do that explicitly on the call side)

that's about a **2** plus maybe some circling around for the other cleanups (e.g. emoji usage)

**Comment by ghudgins** [comment]
reduced proposal sounds good to me

**Comment by ghudgins** [comment]
related https://github.com/flox/flox/issues/693

**Comment by ghudgins** [comment]
❌ ERROR: doesn't seem to be a part of this. seeing some new messages in places too. hard to know the scope of verification for all of this...should we wait to verify it at the end?

**Comment by ysndr** [comment]
The prefix is the next thing I'm looking at
This issue was a bit broad to do all at once

**Comment by ghudgins** [comment]
LGTM on the branch. can close this on merge
