### ISSUE TITLE
python3 xcode-select requirement

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#877]
STR:
* be on a mac
* `sudo rm -rf /Library/Developer/CommandLineTools`
* `flox init`
* `flox activate`

Result: xcode-select prompt for python3
![image](https://github.com/flox/flox/assets/5465514/df19fc54-4edf-4b49-90d0-1c59d62214f1)

Expected: no xcode-select prompt

**Comment by ysndr** [comment]
this pops up because our python `profile.d` script is looking for _any_ installed python on the PATH.
On macos this is by default a stub that pulls up this xcode wizard. 🧙
I don't know if detecting _any_ python was a deliberate decision when this script was first written.

https://github.com/flox/flox/blob/main/pkgdb/src/buildenv/assets/etc/profile.d/0500_python.sh#L8

**Comment by the-wondersmith** [comment]
@ysndr FWIW, you *could* check that `command-line-tools` are installed *at all* with `pkgutil --pkg-info=com.apple.pkg.CLTools_Executables`

Examples:
<img width="471" alt="Screenshot 2024-01-29 at 12 48 17 PM" src="https://github.com/flox/flox/assets/61921871/af5e427a-8c5d-4af5-a72f-990607fe0416">

<img width="392" alt="Screenshot 2024-01-29 at 12 47 53 PM" src="https://github.com/flox/flox/assets/61921871/e5b4b9b4-6d30-4d6b-aa26-99b1b7761da3">
