### ISSUE TITLE
Incompatible Flox PkgDb schema versions... and can't use flox

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#942]
STR:
* unclear
* run `flox search` (or a variety of other commands)

Result:

`ERROR: search encountered an error: error running pkgdb: Incompatible Flox PkgDb schema versions ( 2, 4 )`

Expected: 

no error.

Workaround: 

remove `rm -rf ~/.cache/flox`

**Comment by aakropotkin** [comment]
I believe this is caused by running a _new_ version of `flox` and then later running an older version of `flox`.
It's a rare situation, but one that we should handle more gracefully.

The _current_ recommendation ( in case you encounter this before we can create a proper fix ) is to delete your existing `~/.cache/flox/pkgdb-cache-v2` folder.

For a proper solution we can either:
1. Modify existing _views migration_ code to have it automatically **downgrade** the views definitions in your DB here. 
  a. Currently it only handles upgrades.
3. Do not write views definitions into DBs at all, and include them in queries which use them.
  a. After bumping into a few issues with writing views to the DB I prefer this approach.

**Comment by aakropotkin** [comment]
I cooked up this CLI Team ticket to tackle this.
Let me know if we should pull the ticket or wait: https://github.com/flox/flox/issues/946

**Comment by ghudgins** [comment]
will resolve this with catalog service
